export const CATALOG_TEXTS: Record<string, any> = {
  en: {
    b2bTag: "B2B Trade Bulletins",
    title: "Wholesale Export Catalog 2026",
    subtitle: "Read or download our comprehensive catalog containing chemical test references, shipping weight parameters, load volume distributions, and packaging dimensions.",
    insideHeader: "What is Inside the GilaFruit Catalog?",
    insideDesc: "Our catalog is designed for international retail logistics professionals, import managers, and wholesale partners to review grading standards before placing seasonal orders.",
    bullet1: "Hayward Kiwifruit grading specifications and size charts.",
    bullet2: "Pungency analysis and drying processes for fresh Gilan Garlic.",
    bullet3: "Caspian watermelons: Charleston Gray resistance parameters.",
    bullet4: "Packaging tolerances: cardboard trays, wood baskets, and Styrofoam options.",
    bullet5: "Cold storage ethylene scrubber guidelines.",
    downloadTitle: "Download Digital PDF",
    downloadDesc: "Enter your corporate email below and we will trigger the active export catalog directly to your device.",
    emailInputLabel: "Wholesale Corporate Email",
    submitBtnDefault: "Get Catalog PDF",
    submitBtnDownloading: "Preparing Document...",
    downloadConsent: "By downloading, you consent to receive seasonal product crop availability updates.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "Document Size: 4.8 MB • Pages: 5",
    embedPdfTab: "Interactive PDF Embed",
    simulatedSheetTab: "Digital Preview Sheets",
    embedHeading: "ACTIVE BROWSER NATIVE DOCUMENT EMBED",
    embedSubheading: "Direct PDF Stream Link Available",
    quickPageGuideLabel: "Viewing:",
    quickPageGuideDesc: "Use sidebar thumbnails to quick swap document pages",
    catalogPagesHeading: "Catalog Pages",
    confidentialLabel: "CONFIDENTIAL CATALOGUE • LICENSED CUSTOMERS ONLY",
    contactFooter: "Astara, Iran Sourcing Division Direct Line: +98 21 9109 9091",
    zoomLabel: "Zoom",
    pageLabel: "Page",
    searchPagesPlaceholder: "Search catalog page...",
    alPrint: "✓ Direct wireless print spooler triggered. Connection established to GilaFruit primary Astara office printer on queue port 9100.",
    alSuccess: "✓ Success! The high-definition GilaFruit Trade Brochure and Complete Packing Spec matrix has been dispatched to ",
    dismissBtn: "DISMISS",
    pages: {
      p1: {
        title: "Cover & Technical Preface",
        subtitle: "GilaFruit General wholesale index & packing standards",
        prefaceTitle: "SABZ GOSTARAN GILAN FRUIT CO.",
        docRef: "DOC REF: GF-EXP-2026-V3.4 • CASPIAN EXPORTS DISTRIBUTION",
        dear: "Dear Trade Partners and Freight Specialists,",
        para1: "GilaFruit (licensed under Sabz Gostaran Gilan) is proud to present our standardized technical indexing ledger for international market procurement. Over the past twenty-four calendar years, our packing houses in Astara, Talesh, and Gilan province have specialized in providing premium agricultural commodities matching rigorous international custom guidelines.",
        para2: "This catalog contains essential physical metrics, including caliber-weight index ratios, humidity tolerance curves, and cold-storage parameters necessary for long-distance maritime and ground freight coordinates.",
        orgLabel: "Sourcing Origins",
        orgVal: "Talesh Highlands, Caspian Greenbelt",
        phytoLabel: "Phytosanitary Class",
        phytoVal: "Grade A - Federal EPPO Compliant",
        wareLabel: "CA Warehouse Port",
        wareVal: "Astara Border Customs Hub",
        palletLabel: "Palletized Weight Rate",
        palletVal: "980 Kg net weight standard load",
        copyLabel: "✓ OFFICIAL DIGITAL COPY • FOR LICENSED GilaFruit TRADERS ONLY"
      },
      p2: {
        title: "Hayward Kiwifruit Standards",
        subtitle: "Caliber-weight coordinates and harvesting standards",
        sec: "SECTION 01 // FRESH FRUITS SPECIFICATIONS",
        led: "HAYWARD KIWIFRUIT CALIBRATION LEDGER",
        desc: "Astara Kiwi is characterized by its high sugar accumulation capacity and firm flesh structure. Calibrated automatically via high-frequency weight grader cups down at Astara collection zones.",
        tableHeaders: ["Standard Caliber", "Individual Weight", "Average count per Box", "Target Soluble Sugar brix"],
        items: [
          ["Caliber 25", "130g - 145g", "25 Fruits", "> 7.2 °Bx"],
          ["Caliber 27", "115g - 130g", "27 Fruits", "> 7.0 °Bx"],
          ["Caliber 30", "100g - 110g", "30 Fruits", "> 6.5 °Bx"],
          ["Caliber 33", "85g - 100g", "33 Fruits", "> 6.5 °Bx"],
          ["Caliber 36", "75g - 85g", "36 Fruits", "> 6.2 °Bx"]
        ],
        warnTitle: "Harvesting Limit Pressure Threshold:",
        warnDesc: "We halt raw harvesting when fruit pressure metrics drop below 14 lbs/inch² to guarantee optimal shelf life during extended maritime shipments. Minimum Soluble Solids Content on vessel departure set at > 6.5%."
      },
      p3: {
        title: "Fresh Garlic Curing & Clove Specs",
        subtitle: "Moisture levels and nitrogen storage metrics",
        sec: "SECTION 02 // ALLIUM SATIVUM PARAMETERS",
        led: "GILAN HIGH-PUNGENCY GARLIC CURING MATRIX",
        desc: "Our garlic crop stands out with its heavy sulfur-based compounds and high Allicin output. Our processing houses utilize dry-wind curing tunnels to reduce moisture down to non-rot baselines before packaging dispatch.",
        col1Title: "Curing Protocol",
        col1List: [
          "15 days high-velocity warm air cycle",
          "Root trim standard: Trimmed exactly to 5.0 mm",
          "Foliage stalk height: cut to 15.0 mm maximum",
          "Maximum shell weight moisture loss: 12.4%"
        ],
        col2Title: "Thermodynamic Storage Target",
        col2List: [
          "Optimum Warehouse Temp: -1.5°C to -2.0°C",
          "Relative Humidity Setpoint: 60% to 65% RH",
          "Gas Circulation Ratio: High Nitrogen flushing",
          "Ethylene tolerance threshold: Negative"
        ],
        warnTitle: "Chemical Analysis Index:",
        warnDesc: "Active Allicin concentration averages 4.8 mg/g on dry weight. Ideal for extraction laboratories and pharmaceutical imports in Eastern Europe."
      },
      p4: {
        title: "Caspian Vegetables & Melons Indexes",
        subtitle: "Charleston Gray Watermelon rind tolerances & details",
        sec: "SECTION 03 // VEGETABLES & MELONS SPECIFICATIONS",
        led: "CASPIAN CHARLESTON GRAY RIND DENSITY",
        desc: "Charleston Gray watermelons are highly prioritized by Caspian freight dispatchers because of their thick skin and high resistance during trans-national long haul shipping.",
        stat1Title: "Rind Thickness",
        stat1Val: "1.8 cm - 2.2 cm",
        stat1Sub: "High shock deflection",
        stat2Title: "Avg Sugar Count",
        stat2Val: "11.8% Sucrose",
        stat2Sub: "Sweet Caspian brix",
        stat3Title: "Single Unit Weight",
        stat3Val: "8.5 Kg - 14.5 Kg",
        stat3Sub: "Symmetric shape",
        stowageTitle: "Stowage & Handling Instructions",
        stowageP1: "Watermelons are laid in thick straw beds inside specialized high-sided wooden crates (bulk export parameters). Layer stacking is restricted to 4 layers high maximum to protect the lower levels from excessive static pressure.",
        stowageP2: "Air spaces must be left on the sides using vertical ventilation dividers. Optimum transit ambient temperature is set at +10°C to +12°C. Relative humidity should not exceed 75% to prevent mold formation on stems."
      },
      p5: {
        title: "Packaging Tolerances & Ethylene Control",
        subtitle: "Technical details on box materials and gas scrubbers",
        sec: "SECTION 04 // MATERIAL PHYSICS & GAS THRESHOLDS",
        led: "PACKING COMPONENT PARAMETERS",
        sec1Title: "Waxed Kraftliner Board Resistance",
        sec1Desc: "Our corrugated Kraft cardboard lines are wax impregnated with food-grade paraffin. This guarantees a moisture absorption variance limit of withstanding < 8% weight expansion, even when subjected to 90% atmospheric humidity at zero degrees for over 45 days.",
        sec2Title: "Ethylene Scrubbing Thresholds in CA Rooms",
        sec2Desc: "GilaFruit Astara holding cell zones employ catalytic converters and active potassium permanganate filters to extract ethylene. This keeps local gas concentration within sealed fruit vaults < 0.05 ppm, preventing premature softening or yellowing of leafy greens and kiwi crops.",
        grid1Title: "CARDBOARD COATINGS",
        grid1Val: "Paraffin Water Shield standard",
        grid2Title: "PLASTIC TOXICOLOGY",
        grid2Val: "100% Phthalate and BPA free"
      }
    }
  },
  fa: {
    b2bTag: "اطلاعیه‌های تجاری B2B",
    title: "کاتالوگ جامع صادرات ۲۰۲۶",
    subtitle: "مشاهده آنلاین یا دانلود کاتالوگ دقیق فنی شامل تحلیل گواهینامه‌ها، جداول اوزان بسته‌بندی، پارامترهای بارگیری و ابعاد کارتن‌های صادراتی.",
    insideHeader: "محتویات کاتالوگ گیلافروت چیست؟",
    insideDesc: "این کاتالوگ برای مدیران زنجیره تأمین، تجار بین‌المللی و توزیع‌کنندگان عمده طراحی شده تا ویژگی‌های محصولات را با استانداردهای گمرکی تطبیق دهند.",
    bullet1: "شاخص کالیبر و جدول ابعاد کیوی هایوارد ممتاز.",
    bullet2: "روند کیورینگ و کنترل میزان رطوبت و الیسین سیر گیلان.",
    bullet3: "هندوانه چارلستون گری: بررسی ضخامت پوست جهت حمل طولانی.",
    bullet4: "تلورانس ابعادی بسته‌بندی: کارتن مومی، صندوق چوبی و سبدهای فوم.",
    bullet5: "دستورالعمل جاذب اتیلن و اتمسفر سالن‌های سردخانه.",
    downloadTitle: "دانلود فایل دیجیتال PDF",
    downloadDesc: "ایمیل تجاری خود را وارد کنید تا کاتالوگ کیفیت و گواهینامه‌ها مستقیماً به صندوق ورودی شما ارسال گردد.",
    emailInputLabel: "ایمیل تجاری شرکت شما",
    submitBtnDefault: "دریافت فایل PDF کاتالوگ",
    submitBtnDownloading: "در حال آماده‌سازی سند...",
    downloadConsent: "با کلیک برای دانلود، شما موافقت خود را جهت دریافت آپدیت موجودی هفتگی اعلام می‌نمایید.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "حجم فایل: ۴.۸ مگابایت • صفحات: ۵",
    embedPdfTab: "نمایه تعاملی PDF",
    simulatedSheetTab: "صفحات پیش‌نمایش دیجیتال",
    embedHeading: "نمای تعاملی مرورگر برای لود اسناد",
    embedSubheading: "لینک مستقیم لود سریع PDF در دسترس است",
    quickPageGuideLabel: "در حال مشاهده:",
    quickPageGuideDesc: "از نوار کنار برای ورق زدن برگه استفاده کنید",
    catalogPagesHeading: "صفحات کاتالوگ",
    confidentialLabel: "سند محرمانه تجاری • مخصوص خریداران رسمی گیلافروت",
    contactFooter: "آستارا، ایران - بخش فروش صادراتی: ۹۱۰۹۹۰۹۱ ۲۱ ۹۸+",
    zoomLabel: "بزرگنمایی",
    pageLabel: "صفحه",
    searchPagesPlaceholder: "جستجو در برگه‌ها...",
    alPrint: "✓ چاپ بی‌سیم صادر شد. اتصال به پرینتر گمرک مرزی آستارا روی پورت ۹۱۰۰ برقرار گردید.",
    alSuccess: "✓ موفقیت‌آمیز! بروشور صادراتی و جدول مشخصات جام بسته‌بندی به ایمیل زیر ارسال شد: ",
    dismissBtn: "بستن اعلام",
    pages: {
      p1: {
        title: "جلد و مقدمه فنی کاتالوگ",
        subtitle: "استاندارد فرآیندهای لجستیک و کنترل کیفیت شرکت گیلافروت",
        prefaceTitle: "شرکت سبزگستران گیلان فروت",
        docRef: "کد سند: GF-EXP-2026-V3.4 • توزیع بخش صادرات منطقه کاسپین",
        dear: "تجار، همکاران بین‌المللی و مدیران گرامی فرستنده بار،",
        para1: "مجموعه گیلافروت (دارای پروانه از شرکت سبزگستران گیلان بنیسی) افتخار دارد که نظام‌نامه استانداردهای کیفیت محصولات کشاورزی صادراتی ایران را به عنوان مرجع خرید ثبت نماید. طی بیست و چهار سال گذشته حضور پیاپی، مجمع سردخانه‌ها و خطوط اپتیکال ما در تالش و آستارا همسو با پروتکل‌های بهداشتی گمرک روسیه و اروپا فعالیت داشته است.",
        para2: "این برگه حاوی ابعاد تجربی کانتینر، درصد کاهش طبیعی وزن در مسیر ترانزیت، و شاخص مطلوب اتیلن بوده تا ترخیص کالا بدون کوچک‌ترین مشکل کیفی انجام پذیرد.",
        orgLabel: "مبادی تأمین کالا",
        orgVal: "باغات مازندران و گیلان، گستره سبز بندری کاسپین",
        phytoLabel: "کلاس سلامت بهداشت بهداشت نباتی",
        phytoVal: "رتبه A - صددرصد منطبق با استانداردهای EPPO",
        wareLabel: "گمرک مرزی و ترخیص",
        wareVal: "بندر آستارا و انزلی، گیلان، ایران",
        palletLabel: "وزن استاندارد پالت بارگیری",
        palletVal: "۹۸۰ کیلوگرم خالص کارتن‌گذاری شده ممتاز",
        copyLabel: "✓ سند رسمی الکترونیک • صرفاً جهت استفاده تجار رسمی شرکت گیلافروت"
      },
      p2: {
        title: "استاندارد کیوی هایوارد صادراتی",
        subtitle: "شاخص کالیبر، اوزان خالص و استاندارد برداشت",
        sec: "بخش اول // مشخصات فنی میوه‌های تازه",
        led: "دفترچه رسمی سورتینگ و درجه‌بندی کیوی هایوارد آستارا",
        desc: "کیوی تولیدی باغات شمال با سفتی بافت بالا و قند مناسب شناخته می‌شود که پس از چیدمان به صورت اتوماتیک توسط کاپ‌های حساس دیجیتالی وزن‌کشی می‌گردند.",
        tableHeaders: ["کالیبر استاندارد", "وزن تقریبی هر دانه", "میزان دانه در سبد", "حداقل قند بریکس"],
        items: [
          ["کالیبر ۲۵", "۱۳۰ تا ۱۴5 گرم", "۲۵ دانه", "بیش از ۷.۲"],
          ["کالیبر ۲۷", "۱1۵ تا ۱۳۰ گرم", "۲۷ دانه", "بیش از ۷.۰"],
          ["کالیبر ۳۰", "۱۰۰ تا ۱۱۰ گرم", "۳۰ دانه", "بیش از ۶.۵"],
          ["کالیبر ۳۳", "۸۵ تا ۱۰۰ گرم", "۳۳ دانه", "بیش از ۶.۵"],
          ["کالیبر ۳۶", "۷۵ تا ۸۵ گرم", "۳۶ دانه", "بیش از ۶.۲"]
        ],
        warnTitle: "آستانه سفتی بافت جهت برداشت ایمن:",
        warnDesc: "برداشت محصول زمانی فعال می‌شود که فشارسنج فیزیکی بالاتر از ۱۴ پوند برسد تا ماندگاری ایده آل در کشتی‌های فریزری تضمین شود. حداقل بریکس زمان بارگیری ۶.۵٪ معین شده است."
      },
      p3: {
        title: "کیورینگ سیر سفید خشک گیلان",
        subtitle: "درصد رطوبت نهایی پوسته و اتمسفر گازی سردخانه",
        sec: "بخش دوم // مشخصات و آنالیز آلیوم ساتیوم",
        led: "ماتریس فرآیند رطوبت‌زدایی و کیورینگ سیر ممتاز در بافت",
        desc: "سیر سبز گیلان با داشتن طعم تند فوق‌العاده و سطح الیسین بالا، پس از چیدمان در تونل‌های هوای گرم گیلافروت قرار می گیرد تا رطوبت اضافه جهت جلوگیری از کپک تخلیه شود.",
        col1Title: "پروتکل خشک‌سازی سیر",
        col1List: [
          "۱۵ روز چرخش مداوم هوای گرم کاتالیز شده",
          "سورت طول ریشه: کوتاه شده دقیقا به اندازه ۵ میلی‌متر",
          "ساقه‌بندی شاخه: حداکثر ۱۵ میلی‌متر بالای غلاف",
          "حداکثر کاهش رطوبت پوسته بیرونی: ۱۲.۴٪"
        ],
        col2Title: "پارامترهای فنی اتمسفر انبارداری",
        col2List: [
          "دمای مطلوب سالن سردخانه: منفی ۱.۵ تا منفی ۲ درجه",
          "رطوبت نسبی تعیین شده: ۶۰ الی ۶۵ درصد",
          "نوع گاز اتمسفر: پمپاژ مجاز نیتروژن",
          "حساسیت به گاز اتیلن: کاملاً خنثی"
        ],
        warnTitle: "آنالیز آزمایشگاه شیمیایی مالت:",
        warnDesc: "میزان غلظت ماده فعال الیسین با میانگین ۴.۸ میلی‌گرم بر گرم بسیار ممتاز سنجیده شده که برای صنایع دارویی اروپایی انتخابی بی‌رقیب است."
      },
      p4: {
        title: "شاخص هندوانه چارلستون گری",
        subtitle: "ضخامت پوسته هندوانه و پایداری در ترانزیت جاده‌ای",
        sec: "بخش سوم // مشخصات صیفی‌جات و هندوانه کاسپین",
        led: "آنالیز چگالی پوست و گوشت هندوانه چارلستون گری آستارا",
        desc: "هندوانه صادراتی به علت داشتن ضخامت مناسب پوسته مومی بالاترین پایداری را در کانتینرها بدون ترکیدگی دارند.",
        stat1Title: "ضخامت پوسته",
        stat1Val: "۱.۸ تا ۲.۲ سانتی‌متر",
        stat1Sub: "دفع عالی ارتعاشات مسیر جاده‌ای",
        stat2Title: "میانگین ساکارز طبیعی",
        stat2Val: "۱۱.۸ درصد قند",
        stat2Sub: "طعم فوق عسلی",
        stat3Title: "وزن هر دانه هندوانه",
        stat3Val: "۸.۵ تا ۱۴.۵ کیلوگرم",
        stat3Sub: "قالب بیضی کشیده متقارن",
        stowageTitle: "دستورالعمل بارچینی و مهار کالا",
        stowageP1: "هندوانه‌ها روی بستر ضخیمی از پوشال در صندوق‌های بزرگ چوبی قرار می‌گیرند. ارتفاع بارچینی حداکثر به ۴ طبقه محدود می‌گردد تا از ایجاد فشار استاتیک بر ردیف‌های پایین جلوگیری شود.",
        stowageP2: "دمای داخلی کانتینر باید بین مثبت ۱۰ الی مثبت ۱۲ درجه سانتی‌گراد حفظ شود. رطوبت بالاتر از ۷۵ درصد باعث قارچ گل گلوگاه می‌گردد و ممنوع است."
      },
      p5: {
        title: "جعبه‌های صادراتی و کنترل اتیلن",
        subtitle: "جنس مقوای دیواره کارتن‌ها و کاتالیزورهای ضد پیرشدگی بار",
        sec: "بخش چهارم // ساختار فیزیکی مواد بسته بندی",
        led: "مشخصات فنی قطعات بسته‌بندی پالتایز شده",
        sec1Title: "مقاومت مقاومت کارتن‌های کرافت لاینر مومی",
        sec1Desc: "کارتن‌های ۵ لایه تولیدی ما با موم درجه خوراکی ضدآب شده‌اند که پایداری آن‌ها را حتی در رطوبت بالای ۹۰ درصد سردخانه تا ۴۵ روز تضمین می‌کند بدون اینکه دچار نرمی شوند.",
        sec2Title: "تصفیه مستمر گاز اتیلن سالن‌ها",
        sec2Desc: "در سردخانه‌های اختصاصی گیلافروت با فیلترهای فعال پرمنگنات پتاسیم، سطح گاز اتیلن کمتر از ۰.۰۵ پی‌پی‌ام حفظ می‌شود تا از رسیدگی زودرس و زرد شدن برگ کاهوها کاملاً جلوگیری شود.",
        grid1Title: "پوشش‌های پارافینی ضد رطوبت",
        grid1Val: "استاندارد پارافین واکس خوراکی رسمی",
        grid2Title: "سم‌شناسی پلاستیک‌ها",
        grid2Val: "کاملاً فاقد بی پی ای و سم غلاف پلاستیکی"
      }
    }
  },
  ru: {
    b2bTag: "B2B Торговые Бюллетени",
    title: "Экспортный каталог 2026",
    subtitle: "Ознакомьтесь онлайн или скачайте технический каталог, содержащий химические индексы, весовые параметры тары и размеры упаковок.",
    insideHeader: "Что внутри каталога GilaFruit?",
    insideDesc: "Наш каталог разработан для специалистов международной логистики и импортеров для проверки стандартов калибровки.",
    bullet1: "Спецификации калибровки киви Hayward.",
    bullet2: "Анализ сушки чеснока в Гилане.",
    bullet3: "Параметры прочности арбузов Charleston Gray.",
    bullet4: "Допуски размеров гофрокоробов и ящиков.",
    bullet5: "Нормативы по очистке этилена на прохладных складах.",
    downloadTitle: "Скачать цифровой PDF",
    downloadDesc: "Введите корпоративный email, чтобы получить полный технический каталог напрямую.",
    emailInputLabel: "Рабочий корпоративный Email",
    submitBtnDefault: "Получить PDF",
    submitBtnDownloading: "Подготовка...",
    downloadConsent: "Скачивая, вы соглашаетесь на еженедельное обновление прайс-листов.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "Размер: 4.8 МБ • Страниц: 5",
    embedPdfTab: "Интерактивный PDF",
    simulatedSheetTab: "Цифровой просмотр страниц",
    embedHeading: "ПРОСМОТР ДОКУМЕНТОВ В БРАУЗЕРЕ",
    embedSubheading: "Доступна прямая ссылка на PDF",
    quickPageGuideLabel: "Просмотр:",
    quickPageGuideDesc: "Используйте миниатюры для переключения страниц",
    catalogPagesHeading: "Страницы каталога",
    confidentialLabel: "КОНФИДЕНЦИАЛЬНЫЙ ДОКУМЕНТ",
    contactFooter: "Отдел экспорта Астара: +98 21 9109 9091",
    zoomLabel: "Масштаб",
    pageLabel: "Страница",
    searchPagesPlaceholder: "Поиск по страницам...",
    alPrint: "✓ Печать запущена. Соединение с пограничным принтером Астары установлено.",
    alSuccess: "✓ Готово! Экспортная книга отправлена на почту: ",
    dismissBtn: "ЗАКРЫТЬ",
    pages: {
      p1: {
        title: "Обложка и введение",
        subtitle: "Общие весовые индексы и нормативы упаковки GilaFruit",
        prefaceTitle: "SABZ GOSTARAN GILAN FRUIT CO.",
        docRef: "DOC REF: GF-EXP-2026-V3.4 • CASPIAN EXPORTS",
        dear: "Уважаемые торговые партнеры и логисты,",
        para1: "GilaFruit рада представить технический классификатор для закупки качественных свежих товаров из Ирана. Более 24 лет наши склады в Астаре и Талеше работают по европейским регламентам.",
        para2: "Каталог содержит весовые пропорции калибров, кривую влажности и температуры для надежной сухопутной перевозки.",
        orgLabel: "Место выращивания",
        orgVal: "Зеленый коридор Гилана, Каспийское побережье",
        phytoLabel: "Фитосанитарный класс",
        phytoVal: "Класс А - Соответствует стандартам ЕОКЗР (EPPO)",
        wareLabel: "Таможенный склад хранения",
        wareVal: "Пограничный хаб Астара",
        palletLabel: "Номинальный вес паллеты",
        palletVal: "980 кг нетто стандарта погрузки",
        copyLabel: "✓ ДЛЯ ОФИЦИАЛЬНЫХ КЛИЕНТОВ GILAFRUIT"
      },
      p2: {
        title: "Стандарты Киви Хайвард",
        subtitle: "Калибр-вес и стандарты сбора плодов",
        sec: "РАЗДЕЛ 01 // СПЕЦИФИКАЦИЯ ФРУКТОВ",
        led: "ТАБЛИЦАКАЛИБРОВКИ КИВИ HAYWARD СОРТ А+",
        desc: "Киви Hayward из Астары отличается повышенной плотностью мякоти и идеальным сухим веществом. Сортируется роботами по весу.",
        tableHeaders: ["Стандартный калибр", "Вес единицы", "Количество в ящике", "Сахаристость Brix"],
        items: [
          ["Калибр 25", "130г - 145г", "25 шт", "> 7.2 °Bx"],
          ["Калибр 27", "115г - 130г", "27 шт", "> 7.0 °Bx"],
          ["Калибр 30", "100г - 110г", "30 шт", "> 6.5 °Bx"],
          ["Калибр 33", "85г - 100г", "33 шт", "> 6.5 °Bx"],
          ["Калибр 36", "75г - 85г", "36 шт", "> 6.2 °Bx"]
        ],
        warnTitle: "Предел давления при сборе:",
        warnDesc: "Мы останавливаем сбор урожая, если плотность падает ниже 14 фунтов/дюйм², гарантируя прочность при доставке морем."
      },
      p3: {
        title: "Сушка и калибровка чеснока",
        subtitle: "Параметры влажности оболочки и азотной среды",
        sec: "РАЗДЕЛ 02 // ПАРАМЕТРЫ ALLIUM SATIVUM",
        led: "ТЕХНОЛОГИЧЕСКАЯ КАРТА СУШКИ И ПОДГОТОВКИ ЧЕСНОКА",
        desc: "Иранский чеснок славится высоким выходом аллицина. Мы применяем тепловые камеры с наддувом для удаления сырости.",
        col1Title: "Протокол сушки",
        col1List: [
          "15 дней интенсивной вентиляции воздухом +32C",
          "Длина корня: укорочена до 5.0 мм макс",
          "Высота стебля: 15.0 мм максимум от верхушки",
          "Потеря веса оболочки на сушку: 12.4%"
        ],
        col2Title: "Условия хранения",
        col2List: [
          "Температура склада: -1.5°C до -2.0°C",
          "Относительная влажность: 60-65% RH",
          "Тип газа оболочки: Промывка Азотом (N2)",
          "Чувствительность к этилену: Ноль"
        ],
        warnTitle: "Химический тест:",
        warnDesc: "Концентрация Аллицина составляет в среднем 4.8 мг/г, что высоко ценится фармацевтами в Европе."
      },
      p4: {
        title: "Параметры Арбузов и Овощей",
        subtitle: "Толщина корки арбузов Чарльстон Грей",
        sec: "РАЗДЕЛ 03 // СПЕЦИФИКАЦИЯ ОВОЩЕЙ И БАХЧЕВЫХ",
        led: "ПЛОТНОСТЬ КОЖУРЫ ARBUZ CASPIAN",
        desc: "Арбуз Чарльстон Грей имеет плотную кожуру, что позволяет везти его на тысячи километров без перегрузок.",
        stat1Title: "Толщина корки",
        stat1Val: "1.8 - 2.2 см",
        stat1Sub: "Абсолютная защита от прессования",
        stat2Title: "Уровень сахара",
        stat2Val: "11.8% сукрозы",
        stat2Sub: "Сладкий каспийский вкус",
        stat3Title: "Средний вес плода",
        stat3Val: "8.5 - 14.5 кг",
        stat3Sub: "Калибр одинаковой овальной формы",
        stowageTitle: "Правила Укладки и Транспортировки",
        stowageP1: "Укладывается на толстую солому в деревянные ящичные контейнеры. Высота штабеля ограничена 4 слоями арбузов.",
        stowageP2: "Стандартная температура перевозки составляет +10С до +12С. Влажность не более 75% для избежания грибка плодоножки."
      },
      p5: {
        title: "Анализ коробок и этилена",
        subtitle: "Влагостойкость картона и катализаторы этилена",
        sec: "РАЗДЕЛ 04 // ФИЗИКА МАТЕРИАЛОВ",
        led: "ТЕХНИЧЕСКИЕ ПАРАМЕТРЫ УПАКОВКИ",
        sec1Title: "Влагозащищенный картон Kraftliner",
        sec1Desc: "Наши 5-слойные коробки покрыты пищевым воском. Они не теряют форму при влажности 90% до 45 дней хранения.",
        sec2Title: "Поглотители этилена в камерах CA",
        sec2Desc: "Фильтры на базе перманганата калия держат уровень этилена в камерах ниже 0.05 ppm, устраняя раннее увядание зелени.",
        grid1Title: "ПОКРЫТИЕ КАРТОНА",
        grid1Val: "Пищевой защитный парафин стандарт",
        grid2Title: "ТОКСИКОЛОГИЯ ПЛАСТИКА",
        grid2Val: "100% без Фталатов и Бисфенола (BPA free)"
      }
    }
  },
  ar: {
    b2bTag: "النشرات التجارية B2B",
    title: "كتالوج الجودة والتصدير ٢٠٢٦",
    subtitle: "تصفح أو قم بتحميل ملف الكتالوج الزراعي الفني الذي يشمل أبعاد التعبئة وجداول أوزان الحاويات ومستويات اتیلن.",
    insideHeader: "ماذا يحتوي كتالوج كيلافروت؟",
    insideDesc: "هذا الدليل مهيأ لوكلاء الشحن ومدراء التوريد الخارجيين للتأكد من المعايير قبل كتابة طلبات الأسعار الموسمية.",
    bullet1: "معايير تدرج العيار والأبعاد لثمار الكيوي الإيراني.",
    bullet2: "تحليل نسبة المياه وتطهير فصوص الثوم بالأكسجين.",
    bullet3: "مستويات ثبات وقشرة بطيخ تشارلستون غراي الفاخر.",
    bullet4: "مواصفات تفاوت حجم كرتون محزز مائل مبرد وصندوق خشب.",
    bullet5: "شروط وضوابط تنقية الغازات داخلVault التبريد.",
    downloadTitle: "تنزيل الكتالوج الرقمي PDF",
    downloadDesc: "ضع بريدك الإلكتروني المؤسسي ليقوم نظامنا التلقائي بإرسال بروشور الاسعار والتعبئة حالاً.",
    emailInputLabel: "البريد الإلكتروني التجاري للشركة",
    submitBtnDefault: "الحصول على الكتالوج PDF",
    submitBtnDownloading: "جاري إعداد السند الزراعي...",
    downloadConsent: "بالضغط، تقبل استلام جداول النضج الأسبوعية عبر بريدك.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "حجم السند: ٤.٨ مياغابايت • الصفحات: ٥",
    embedPdfTab: "نموذج PDF التفاعلي",
    simulatedSheetTab: "صفحات العرض المباشر",
    embedHeading: "عرض تفاعلي مباشر داخل المتصفح لسجلات الشحن",
    embedSubheading: "رابط التنزيل السريع مباشر ونشط بالكامل",
    quickPageGuideLabel: "الصفحة المعروضة:",
    quickPageGuideDesc: "استخدم الصور الجانبية للتنقل بين أوراق الكتالوج",
    catalogPagesHeading: "صفحات الكتالوج",
    confidentialLabel: "سند تجاري سري وخاضع للتصدير الرسمي حصراً مرخصين",
    contactFooter: "آستارا، إيران - الخط الساخن لقسم المبيعات: ٩١٠٩٩٠٩١ ٢١ ٩٨+",
    zoomLabel: "تكبير",
    pageLabel: "صفحة",
    searchPagesPlaceholder: "البحث في الصفحات...",
    alPrint: "✓ تم إرسال أمر السحب اللاسلكي. الاتصال تفاعلي بنجاح بمطبعة جمرك أستارا على المدخل ٩١٠٠.",
    alSuccess: "✓ ممتاز! تم إرسال ملف Specifications ومصفوفة الأحجام بنجاح إلى: ",
    dismissBtn: "إلغاء الإعلا",
    pages: {
      p1: {
        title: "الغلاف والتمهيد الفني للكتالوج",
        subtitle: "معايير الوزن الشامل لشركة كيلافروت ونظام الفواتير الموحد",
        prefaceTitle: "شركة سبز كستران جيلان فروت المساهمة",
        docRef: "المرجع: DOC REF: GF-EXP-2026-V3.4 • توزيع كاسبيان الرسمي",
        dear: "السادة الشركاء الموقرين والخبراء اللوجستيين الدوليين،",
        para1: "تتشرف شركة كيلافروت بوضع دليل الحسابات القياسي للمحاصيل الزراعية المصدرة من مزارع جيلان. منذ ما يزيد على أربعة وعشرين عاماً دأبت خطوطنا الآلية في تالش على فرز وتصدير البضائع لأسواق روسيا والشرق الأوسط وفق بروتوكولات حازمة.",
        para2: "يحتوي هذا السند على أبعاد الكرتون ونسب الحفظ داخل غرف التحكم ودرجة الغليان الموصى بها لتفوق بضائعنا المنافسين.",
        orgLabel: "مباديء جني المحاصيل",
        orgVal: "مرتفعات تالش، حزام كاسبيان الأخضر الإيراني",
        phytoLabel: "رتبة شهادة الصحة النباتية",
        phytoVal: "درجة A ممتاز - مطابقة تماماً للمقاييس الفيدرالية EPPO",
        wareLabel: "موقع مخازن التبريد والجمارك",
        wareVal: "بندر أستارا الجمركي، جيلان، إيران",
        palletLabel: "الوزن الصافي المعتمد لوحدة البالت",
        palletVal: "٩٨٠ كجم شحنات مغلفة مغطاة بشمع البارافين",
        copyLabel: "✓ نسخة إلكترونية رسمية ممتازة محرمة لغير الشركاء والعملاء"
      },
      p2: {
        title: "بيان ثمار الكيوي الإيراني ممتاز",
        subtitle: "تدرج حجم العيار ومقاييس الضغط للحصاد الآمن",
        sec: "القسم الأول // الكيوي ثمار ونسب تجميعها",
        led: "جريدة تصنيف وفرز الكيوي هایوارد آستارا آلياً",
        desc: "تتميز ثمار الكيوي من مزارع جيلان بمقاومتها العالية للحفظ وسماكة قشرتها المبررة التي تقاوم النقل البحري، وتفرز بآلات الطرد بالوزن الحساس.",
        tableHeaders: ["العيار والعدد بالكرتون", "الوزن التقريبي للحبة", "نسب الحجم والتجانس", "أدنى درجة سكر بريكس"],
        items: [
          ["عيار ٢٥", "١٣٠ جرام - ١٤٥ جرام", "٢٥ ثمرة مصفوفة", "أعلى من ٧.٢"],
          ["عيار ٢٧", "١١٥ جرام - ١٣٠ جرام", "٢٧ ثمرة مصفوفة", "أعلى من ٧.٠"],
          ["عيار ٣٠", "١٠٠ جرام - ١١٠ جرام", "٣٠ ثمرة مصفوفة", "أعلى من ٦.٥"],
          ["عيار ٣٣", "٨٥ جرام - ١٠٠ جرام", "٣٣ ثمرة مصفوفة", "أعلى من ٦.٥"],
          ["عيار ٣٦", "٧٥ جرام - ٨٥ جرام", "٣٦ ثمرة مصفوفة", "أعلى من ٦.٢"]
        ],
        warnTitle: "أدنى ضغط باسكال معتمد للقطف:",
        warnDesc: "يتم إيقاف جني البساتين حال نزول منسوب رطوبة الغلاف عن ١٤ رطلا بالبوصة للتخزين طويل المدة لضمان عيار سليم غير لزج."
      },
      p3: {
        title: "خطوات تجفيف وتطهير ثوم غيلان",
        subtitle: "تقليل رطوبة الحواشي وغاز النتروجين بالبرادات",
        sec: "القسم الثاني // معايير اليوليم ساتيوم التصدير",
        led: "كشف نسب تجفيف فصوص الثوم الأبيض المقلم",
        desc: "يمتاز ثوم مزارع جيلان بالطعم اللاسع الغني بعناصر الاليوم المقوية ويخضع لفرن غمر الهواء الساخن قبل تدشين مرحلة التعليب لوأد الفطريات.",
        col1Title: "طريقة تطهير الثوم",
        col1List: [
          "١٥ يوما غسيل غاز ساخن مضاد للذبول",
          "سورت طول الجذور: لا يتجاوز ٥.٠ مم بدقة متناهية",
          "ارتفاع أعواد النبات: ١٥.٠ مم حد أقصى فوق القشرة",
          "معدل هبوط الرطوبة بالبصل: ١٢.٤٪"
        ],
        col2Title: "مواصفات تبريد غرف النيتروجين",
        col2List: [
          "الحرارة المعتمدة للغرف: من سالب ١.٥ إلى سالب ٢ درجة",
          "نسبة التبخر المطلوبة: من ٦٠ إلى ٦٥ ٪",
          "نوع الضخ الغازي: غمر النتروجين المركز",
          "التفاعل مع غاز الإثيلين: منفي تماماً"
        ],
        warnTitle: "بيان التحليل الكيمائي المخبري:",
        warnDesc: "معدل الاليوم السكرى النشط بلغ ٤.٨ مجم بالجرام الجاف وهو الأعلى للشركات الصيدلية ومختبرات التجميل بأوروبا."
      },
      p4: {
        title: "مصفوفة هندوانة تشارلستون غري",
        subtitle: "سمك قشرة البطيخ وثلاثية الحفظ في عربات التبريد",
        sec: "القسم الثالث // صنف البطيخ وحصاده",
        led: "كشف أوزان ونسب سماكة جدار بطيخ كاسبيان تشارلستون",
        desc: "يعتلي البطيخ الإيراني مكانة عالية بقشرته الفولاذية الملساء التي تتحمل ضغط الطرق البرية للبلدان المجاورة.",
        stat1Title: "سمك القشرة",
        stat1Val: "١.٨ سم - ٢.٢ سم",
        stat1Sub: "امتصاص مدهش ومقاومة للاصطدام",
        stat2Title: "نسبة السكر الكلية",
        stat2Val: "١١.٨ ٪ محتوى سكروز",
        stat2Sub: "مذاق حلو طبيعي طري",
        stat3Title: "وزن الحبة الواحدة برأس البستان",
        stat3Val: "٨.٥ كجم - ١٤.5 كجم",
        stat3Sub: "هيكل بيضاوي متناسق متناظر",
        stowageTitle: "توصية التحميل والشحن بالجرار",
        stowageP1: "يفرش البطيخ على طبقة كثيفة من القش النظيف في صناديق خشبية مدمجة ويمنع الارتفاع لأكثر من ٤ أدوار تجنباً للتكسر.",
        stowageP2: "الحرارة المطلوبة داخل اللوري البري بين ١٠ و ١٢ درجة مئوية لمنع جفاف العنق، والتهاون بالرطوبة يعرض الثمار للعفن الفطري."
      },
      p5: {
        title: "كرتون التصدير والتحكم اللوجستي بارزان",
        subtitle: "تحليل جودة الكرتون المومى وجاذب اتیلن بمخازن گیلان",
        sec: "القسم الرابع // صلب المواد ومعايير الضغط",
        led: "كشف جودة وحسابات الطرود البلاستيكية والورقية صادرات",
        sec1Title: "مقاومة كرتون Kraftliner خماسي الطبقات المومى",
        sec1Desc: "الواح الكرتون معالجة بشمع غروي غذائي يمنع امتصاص الماء وتآكل ألياف السليلوز حتى رطوبة ٩٠٪ لمدة ٤٥ يوما كاملة بالبراد.",
        sec2Title: "تجهيزات كنس الإثيلين بصالات CA",
        sec2Desc: "ندعم غرف الحفظ بمصافي البوتاسيوم كيمائية لتخفيض منسوب اتیلن لأقل من ٠.۰٥ جزء بالمليون للحفاظ على لون وقوام أوراق خس رومين دون مرارة.",
        grid1Title: "لمينات طلاء المغلف الورقي",
        grid1Val: "شمع بارافين غذائي رسمي معزول تماماً",
        grid2Title: "تقرير خلو غلاف بلاستيك من سموم فتالات",
        grid2Val: "تقرير طبي معتمد فري ١٠٠٪ من مادة BPA الضارة"
      }
    }
  },
  tr: {
    b2bTag: "B2B İhracat Duyuruları",
    title: "Toptan İhracat Kataloğu 2026",
    subtitle: "Ambalaj ebatları, koli dayanıklılık testleri, palet dizilim çizelgeleri ve taze meyve kimyasal analizlerini içeren kapsamlı kataloğumuzu inceleyin.",
    insideHeader: "GilaFruit Kataloğu Neleri İçeriyor?",
    insideDesc: "Kataloğumuz, toptan alıcılar, uluslararası satınalma yöneticileri ve sebze meyve ithalatçıları için kalite standartlarımızı göstermek üzere hazırlanmıştır.",
    bullet1: "Hayward kivi boyutları ve ağırlık kalibrasyonu.",
    bullet2: "Gilan sarımsağı kurutma ve nem kontrol işlemleri.",
    bullet3: "Charleston Gray karpuz kabuk mukavemeti ve araba istiflemesi.",
    bullet4: "Parafinli nem geçirmez kutu ve tahta sandık toleransları.",
    bullet5: "Kontrollü soğuk odalarda etilen filtresi çalıştırma kuralları.",
    downloadTitle: "Dijital PDF Kataloğu İndir",
    downloadDesc: "Kurumsal e-posta adresinizi yazarak güncel ihracat kataloğunun bir kopyasını hemen indirebilirsiniz.",
    emailInputLabel: "Şirket Resmi E-Posta Adresi",
    submitBtnDefault: "Kataloğu İndir (PDF)",
    submitBtnDownloading: "Döküman Hazırlanıyor...",
    downloadConsent: "Dökümanı indirerek haftalık fiyat listelerimizin mailinize ulaşmasını kabul etmiş olursunuz.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "Belge Boyutu: 4.8 MB • Sayfa: 5",
    embedPdfTab: "İnteraktif PDF Görünümü",
    simulatedSheetTab: "Dijital Sayfa Önizleme",
    embedHeading: "TARAYICI İÇİ DOĞRUDAN BELGE GÖRÜNTÜLEME",
    embedSubheading: "Doğrudan indirme bağlantısı aktiftir",
    quickPageGuideLabel: "Gösterilen Sayfa:",
    quickPageGuideDesc: "Yandaki küçük resimleri tıklayarak sayfalar arasında geçiş yapın",
    catalogPagesHeading: "Katalog Sayfaları",
    confidentialLabel: "TİCARİ GİZLİ SÖZLEŞME • Sadece resmi alıcılar için geçerlidir",
    contactFooter: "Astara Merkez Satış Hattı: +98 21 9109 9091",
    zoomLabel: "Yakınlaştır",
    pageLabel: "Sayfa",
    searchPagesPlaceholder: "Sayfalarda ara...",
    alPrint: "✓ Kablosuz baskı komutu gönderildi. Astara sınır gümrük yazıcısı port 9100 bağlantısı aktif hale geldi.",
    alSuccess: "✓ Başarılı! Paketleme spesifikasyon tablosu ve ihracat broşürü şu adrese gönderilmiştir: ",
    dismissBtn: "KAPAT",
    pages: {
      p1: {
        title: "Kapak ve Teknik Giriş",
        subtitle: "GilaFruit Genel toptan satış kalibre indisi ve ambalaj standartları",
        prefaceTitle: "SABZ GOSTARAN GILAN FRUIT CO.",
        docRef: "BELGE REF: GF-EXP-2026-V3.4 • HAZAR BÖLGESİ DAĞITIM",
        dear: "Değerli İthalatçı Ortaklarımız ve Lojistik Yöneticileri,",
        para1: "GilaFruit (Sabz Gostaran Gilan kuruluşu) olarak uluslararası piyasalarda güvenilir taze ürün satınalımı yapabilmeniz için teknik katalog rehberimizi sunmaktan gurur duyarız. 24 yılı aşkın süredir Astara ve Talesh tesislerimiz, gümrük geçişlerine tam uyumlu taze sevkiyatlar yapmaktadır.",
        para2: "Rehberimiz, karayolu ve deniz taşımacılığı sırasında ürünlerin kalitesini korumak için gerekli kalibre tablolarını, depolama nem seviyelerini ve etilen kurallarını içermektedir.",
        orgLabel: "Üretim Havzası",
        orgVal: "Talesh Bölgesi, Hazar Denizi Yeşil Kuşağı, İran",
        phytoLabel: "Fitosanitasyon Sınıfı",
        phytoVal: "Sınıf A - Federal Avrupa Bitki Sağlığı Teşkilatı (EPPO) Uyumlu",
        wareLabel: "Depolama ve Gümrük Çıkışı",
        wareVal: "Astara Sınır Gümrük İstasyonu",
        palletLabel: "Palet Başı Nominal Brüt Ağırlık",
        palletVal: "980 Kg net kutulu palet dizilim",
        copyLabel: "✓ YERLİ VE YABANCI RESMİ ALICILAR İÇİN RESMİ BELGEDİR"
      },
      p2: {
        title: "Hayward Kivi Standartları",
        subtitle: "Boyut kalibrasyonu ve doğru hasat sertlik sınırları",
        sec: "BÖLÜM 01 // TAZE MEYVE ÖZELLİKLERİ",
        led: "HAYWARD KİVİ KALİBRASYON CETVELİ",
        desc: "Kuzey İran kivi bahçeleri yüksek sertlik ve mükemmel koku birikimi ile bilinir. Ürünlerimiz son teknoloji optik tartım haznelerinde el değmeden ayrıştırılır.",
        tableHeaders: ["Standart Kalibre", "Tane Ağırlığı", "Koli İçi Adet", "Brix Şeker Değeri"],
        items: [
          ["Kalibre 25", "130g - 145g", "25 Kivi", "> 7.2 °Bx"],
          ["Kalibre 27", "115g - 130g", "27 Kivi", "> 7.0 °Bx"],
          ["Kalibre 30", "100g - 110g", "30 Kivi", "> 6.5 °Bx"],
          ["Kalibre 33", "85g - 100g", "33 Kivi", "> 6.5 °Bx"],
          ["Kalibre 36", "75g - 85g", "36 Kivi", "> 6.2 °Bx"]
        ],
        warnTitle: "Hasat Sınırı Basınç Eşiği:",
        warnDesc: "Deniz aşırı nakliyelerde yumuşamayı önlemek amacıyla meyve sertliği 14 lbs/inch² değerinin altına düştüğünde hasadı durduruyoruz. Çıkış anındaki şeker oranı minimum > 6.5% olmalıdır."
      },
      p3: {
        title: "Taze Sarımsak Kurutma Detayları",
        subtitle: "Kabuk nem dengesi ve depolama odası özellikleri",
        sec: "BÖLÜM 02 // ALLIUM SATIVUM PARAMETRELERİ",
        led: "GILAN KURU SARIMSAK MUKAVEMET VE KALİTE MATRİSİ",
        desc: "Gilan sarımsağı yüksek keskinlik ve allisin seviyesi ile bilinir. Kurutma tünellerimizde kabuk nem düzeyi çürümeyi önleyen seviyelere indirilir.",
        col1Title: "Kurutma Kuralları",
        col1List: [
          "15 gün sürekli sıcak hava sirkülasyonu",
          "Kök kesim kuralı: Tam olarak 5.0 mm kesim",
          "Sap yüksekliği: Kabuk üzerinden maksimum 15.0 mm",
          "Kurutma sırasındaki kabuk ağırlık kaybı: %12.4"
        ],
        col2Title: "Hassas Gaz Depolama Şartları",
        col2List: [
          "İdeal Depolama Sıcaklığı: -1.5°C ile -2.0°C arası",
          "Önerilen Bağıl Nem: %60 - %65 RH",
          "Gaz Karışım Tipi: Azot (N2) basma koruması",
          "Etilen Duyarlılığı: Tamamen nötr"
        ],
        warnTitle: "Kimyasal Yapı Analiz Notu:",
        warnDesc: "Aktif Allisin konsantrasyonu kuru ağırlıkta ortalama 4.8 mg/g ölçülmüştür, bu değer Avrupa kimya ve ilaç sanayii için oldukça uygundur."
      },
      p4: {
        title: "Karpuz ve Sebze Özellikleri",
        subtitle: "Charleston Gray Karpuz kabuk yapısı ve nakliye kuralları",
        sec: "BÖLÜM 03 // SEBZE VE BOSTAN GRUBU ANALİZLERİ",
        led: "HAZAR BÖLGESİ CHARLESTON GRAY KABUK DEĞERLERİ",
        desc: "İran karpuzları, kalın ve esnek kabuk dokuları sayesinde tır ve gemi nakliyelerinde ezilmeden uzun mesafeleri kaldırabilir.",
        stat1Title: "Kabuk Kalınlığı",
        stat1Val: "1.8 cm - 2.2 cm",
        stat1Sub: "Şok ve darbelere karşı yüksek direnç",
        stat2Title: "Ortalama Şeker Oranı",
        stat2Val: "%11.8 Sukroz",
        stat2Sub: "Meşhur tatlı Hazar lezzeti",
        stat3Title: "Tek Karpuz Ağırlığı",
        stat3Val: "8.5 Kg - 14.5 Kg",
        stat3Sub: "Düzgün oval ve pürüzsüz şekil",
        stowageTitle: "İstifleme ve Yerleştirme Kuralları",
        stowageP1: "Karpuzlar özel tahta kasalar içerisine kalın saman yatakları serilerek dizilir. Üst üste istifleme alt sıradaki karpuzların ezilmemesi için maksimum 4 sıra ile sınırlandırılmalıdır.",
        stowageP2: "Taşıma anındaki sıcaklık +10C ile +12C arası sabit tutulmalıdır. %75 değerini aşan bağıl nem sap kısmında mantar oluşumuna sebep olur."
      },
      p5: {
        title: "Karton Koli ve Etilen Filtresi",
        subtitle: "Parafin kaplı karton dayanıklılığı ve soğuk hava gaz dengesi",
        sec: "BÖLÜM 04 // AMBALAJ FİZİĞİ VE KORUYUCU ATOMİZERLER",
        led: "TEKNİK AMBALAJ VE MALZEME TESTLERİ",
        sec1Title: "Mum Kaplı Kraftliner Koli Mukavemeti",
        sec1Desc: "5 katmanlı ithalat mukavvalarımız gıda sınıfı doğal parafin ile kaplanmıştır. Bu kaplama kolinin sıfır derecede ve %90 nemde 45 gün boyunca yumuşamadan durmasını garantiler.",
        sec2Title: "Etilen Arındırma Eşiği",
        sec2Desc: "GilaFruit depolarında yer alan potasyum permanganatlı aktif filtreler sayesinde odadaki etilen gaz miktarı 0.05 ppm seviyesinin altında tutulur ve yapraklı sebzelerin sararması önlenir.",
        grid1Title: "AMBALAJ MODELİ",
        grid1Val: "BPA ve fitalat içermeyen gıdaya uygun parafin kaplama",
        grid2Title: "KORUYUCU PLASTİKLER",
        grid2Val: "Gıda tüzüğüne tam uyumlu steril ambalaj malzemesi"
      }
    }
  },
  hi: {
    b2bTag: "B2B व्यापार बुलेटिन",
    title: "थोक निर्यात कैटलॉग 2026",
    subtitle: "पैकेजिंग आयाम, बॉक्स शक्ति परीक्षण, पैलेट स्टैकिंग चार्ट और ताजा फल रासायनिक विश्लेषण सहित हमारे व्यापक कैटलॉग की समीक्षा करें।",
    insideHeader: "कैटलॉग में क्या शामिल है?",
    insideDesc: "हमारा कैटलॉग थोक खरीदारों, अंतर्राष्ट्रीय खरीद प्रबंधकों और निर्यातकों के लिए हमारी गुणवत्ता और मानकों को प्रदर्शित करने के लिए तैयार किया गया है।",
    bullet1: "हेवर्ड कीवी फलों का वजन वर्गीकरण और आयाम चार्ट।",
    bullet2: "गिलान लहसुन सुखाने और नमी नियंत्रण प्रक्रिया का विश्लेषण।",
    bullet3: "चार्ल्सटन ग्रे तरबूज त्वचा शक्ति और परिवहन नियम।",
    bullet4: "पैराफिन नमी प्रतिरोधी बक्से और लकड़ी के टोकरे की विशेषताएं।",
    bullet5: "शीत गृह में एथिलीन फिल्टर चलाने के निर्देश।",
    downloadTitle: "डिजिटल पीडीएफ कैटलॉग डाउनलोड करें",
    downloadDesc: "कैटलॉग प्राप्त करने के लिए कॉर्पोरेट ईमेल दर्ज करें।",
    emailInputLabel: "कंपनी का कॉर्पोरेट ईमेल",
    submitBtnDefault: "कैटलॉग डाउनलोड करें (पीडीएफ)",
    submitBtnDownloading: "दस्तावेज़ तैयार किया जा रहा है...",
    downloadConsent: "डाउनलोड करके, आप हमारे साप्ताहिक मूल्य सूचियों को प्राप्त करने के लिए सहमत होते हैं।",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "फ़ाइल का आकार: 4.8 एमबी • पृष्ठ: 5",
    embedPdfTab: "इंटरैक्टिव पीडीएफ देखें",
    simulatedSheetTab: "डिजिटल प्रिव्यू शीट्स",
    embedHeading: "ब्राउज़र में दस्तावेज़ देखें",
    embedSubheading: "सीधे डाउनलोड करने का लिंक सक्रिय है",
    quickPageGuideLabel: "सक्रिय पृष्ठ:",
    quickPageGuideDesc: "पृष्ठ बदलने के लिए साइडबार थंबनेल का उपयोग करें",
    catalogPagesHeading: "कैटलॉग पृष्ठ",
    confidentialLabel: "व्यावसायिक गोपनीय दस्तावेज़ • केवल लाइसेंस प्राप्त उपयोगकर्ताओं के लिए",
    contactFooter: "आस्तरा मुख्य कार्यालय: +98 21 9109 9091",
    zoomLabel: "ज़ूम",
    pageLabel: "पृष्ठ",
    searchPagesPlaceholder: "खोजें...",
    alPrint: "✓ वायरलेस प्रिंट spooler स्थापित किया गया। आस्तरा सीमा कार्यालय प्रिंटर से संपर्क हुआ।",
    alSuccess: "✓ सफल! विनिर्देश तालिका और निर्यात पुस्तिका को इस पते पर भेजा गया है: ",
    dismissBtn: "बंद करें",
    pages: {
      p1: {
        title: "कवर और तकनीकी प्रस्तावना",
        subtitle: "गीलाफ्रूट जनरल थोक सूचकांक और पैकेजिंग विनिर्देश",
        prefaceTitle: "सब्ज़ गोस्तारन गिलान फ्रूट कंपनी",
        docRef: "दस्तावेज़ संदर्भ: GF-EXP-2026-V3.4 • कैस्पियन क्षेत्र निर्यात",
        dear: "प्रिय व्यापार भागीदारों और रसद विशेषज्ञों,",
        para1: "गीलाफ्रूट को अंतर्राष्ट्रीय मानकों के अनुकूल कृषि उत्पादों की अपनी मूल्यवान श्रृंखला प्रस्तुत करने पर गर्व है। पिछले 24 वर्षों से, आस्तरा और तालेह में स्थित हमारी पैकेजिंग इकाइयां निर्यात गुणवत्ता के उत्कृष्ट उत्पाद प्रदान कर रही हैं।",
        para2: "इस विवरणिका में पैकेजिंग के आयाम, तापमान अनुकूलन नियम और एथिलीन नियंत्रण मानदंड शामिल हैं जो लंबी परिवहन दूरी में सहायक हैं।"
      },
      p5: {
        title: "पैकेजिंग विनिर्देश",
        subtitle: "करात कार्डबोर्ड की मजबूती और एथिलीन नियंत्रण नियम"
      }
    }
  },
  uz: {
    b2bTag: "B2B Eksport Yangiliklari",
    title: "Ulgurji Eksport Katalogi 2026",
    subtitle: "Qadoqlash standartlari, qutilar chidamlilik ko'rsatgichlari, yuk hajmlari va mahsulotlar kimyoviy tahlillarini o'z ichiga olgan batafsil katalogimizni yuklang.",
    insideHeader: "Katalog ichida nimalar bor?",
    insideDesc: "Bizning katalogimiz xalqaro ta'minot menejerlari hamda ulgurji meva-sabzavot xaridorlariga sifat ko'rsatgichlarimizni taqdim etish uchun tayyorlangan.",
    bullet1: "Hayward kivi kalibrlari va o'lchov parametrlari.",
    bullet2: "Gilon sarimsoqlarining quritilishi va namlik o'lchovlari.",
    bullet3: "Charleston Gray tarvuzlari chidamliligi va turg'unligi.",
    bullet4: "Parafinlangan suv o'tkazmaydigan karton quti va yog'och yashik normalari.",
    bullet5: "Zamonaviy sovuq xonalarda etilen filtrlarini ishlatish qoidalari.",
    downloadTitle: "Raqamli PDF Katalogni Yuklash",
    downloadDesc: "Korporativ elektron pochtangizni yozib, eng so'nggi eksport katalogimizni hoziroq yuklab oling.",
    emailInputLabel: "Tashkilot Rasmiy Elektron Pochtasi",
    submitBtnDefault: "Katalogni Yuklab Olish (PDF)",
    submitBtnDownloading: "Hujjat Tayyorlanmoqda...",
    downloadConsent: "Hujjatni yuklab, haftalik narx takliflarimizni pochtangizga qabul qilishga rozilik bildirasiz.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "Hujjat hajmi: 4.8 MB • Sahifalar: 5",
    embedPdfTab: "Interaktiv PDF Ko'rinishi",
    simulatedSheetTab: "Raqamli Sahifalar Ko'rinishi",
    embedHeading: "BRAUZER ICHIDA HUJJATNI KO'RISH",
    embedSubheading: "To'g'ridan-to'g'ri yuklash havolasi faol",
    quickPageGuideLabel: "Ko'rilayotgan sahifa:",
    quickPageGuideDesc: "Sahifalarni o'tkazish uchun yon paneldagi kichik rasmlardan foydalaning",
    catalogPagesHeading: "Katalog Sahifalari",
    confidentialLabel: "TJORIY MAXFIY HUJJAT • Faqat GilaFruit mijozlari uchun amal qiladi",
    contactFooter: "Astara Sotuvlar Bo'limi Aloqa Hattining Raqami: +98 21 9109 9091",
    zoomLabel: "Kattalashtirish",
    pageLabel: "Sahifa",
    searchPagesPlaceholder: "Sahifalardan izlash...",
    alPrint: "✓ Chop etish buyrug'i jo'natildi. Astara chegara printeriga ulanish o'rnatildi.",
    alSuccess: "✓ Muvaffaqiyatli! Qadoqlash ko'rsatgichlari va eksport broshurasi quyidagi pochtaga yuborildi: ",
    dismissBtn: "YOPISH",
    pages: {
      p1: {
        title: "Muqova va Texnik Kirish",
        subtitle: "GilaFruit umumiy ulgurji kalibrlar va qadoqlash ko'rsatgichlari",
        prefaceTitle: "SABZ GOSTARAN GILAN FRUIT CO.",
        docRef: "HUJJAT KODI: GF-EXP-2026-V3.4 • HAZAR HUZURI EKSPORT",
        dear: "Dearli Hamkorlar va Logistika Tashkilotchilari,",
        para1: "GilaFruit uzoq muddatli xalqaro savdolar uchun tayyorlangan texnik katalogini sizga taqdim etishdan mamnunmiz. Talesh va Astara bo'limlarimiz bojxona va sifat nazoratidan ideal muvaffaqiyat bilan o'tib kelmoqda.",
        para2: "Ushbu qo'llanmada transport va saqlash amallari davomida mahsulot yangiligini saqlash bo'yicha muhim parametrlar bor."
      }
    }
  },
  az: {
    b2bTag: "B2B İxracat Bildirişləri",
    title: "Topdansatış İxrac Kataloqu 2026",
    subtitle: "Karton qutuların dözümlülük göstəriciləri, palet ölçüləri, yük həcmləri və kimyəvi keyfiyyət tahlillərini özündə birləşdirən ətraflı kataloqumuzu yükləyin.",
    insideHeader: "Kataloqun İçində Nələr Var?",
    insideDesc: "Kataloqumuz, topdansatış alıcıları, beynəlxalq satınalma rəhbərləri və meyvə-tərəvəz idxalatçıları üçün xüsusi olaraq hazırlanmışdır.",
    bullet1: "Hayward kivi ölçüləri və çəki standartları.",
    bullet2: "Gilan sarımsağının qurudulması prosesi və rütubət meyarları.",
    bullet3: "Charleston Gray qarpızlarının qabıq qalınlığı və nəqliyyat qaydaları.",
    bullet4: "Parafinlənmiş su keçirməyən karton qutu və taxta yeşik normaları.",
    bullet5: "Müasir soyuq anbarlarda etilen filtrlərindən istifadə standartları.",
    downloadTitle: "Rəqəmsal PDF Kataloqu Yüklə",
    downloadDesc: "Korporativ elektron poçt ünvanınızı yazaraq cari ixrac kataloqunu dərhal yükləyə bilərsiniz.",
    emailInputLabel: "Təşkilatın Rəsmi E-Poçt Ünvanı",
    submitBtnDefault: "Kataloqu Yüklə (PDF)",
    submitBtnDownloading: "Sənəd Hazırlanır...",
    downloadConsent: "Sənədi yükləyərək həftəlik qiymət təkliflərimizi e-poçtunuza qəbul etməyə razılıq verirsiniz.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "Sənəd Həcmi: 4.8 MB • Səhifə: 5",
    embedPdfTab: "İnteraktiv PDF Görünüşü",
    simulatedSheetTab: "Rəqəmsal Səhifə Önizləməsi",
    embedHeading: "BRAUZER DAXİLİ SƏNƏD GÖRÜNTÜLƏMƏSİ",
    embedSubheading: "Birbaşa yükləmə keçidi aktivdir",
    quickPageGuideLabel: "Göstərilən Səhifə:",
    quickPageGuideDesc: "Səhifələr arasında keçid etmək üçün yan paneldəki kiçik şəkillərdən istifadə edin",
    catalogPagesHeading: "Kataloq Səhifələri",
    confidentialLabel: "TİCARİ GİZLİ SƏNƏD • Sırf GilaFruit rəsmi müştəriləri üçün keçərlidir",
    contactFooter: "Astara Mərkəzi Satış Şöbəsi: +98 21 9109 9091",
    zoomLabel: "Yaxınlaşdır",
    pageLabel: "Səhifə",
    searchPagesPlaceholder: "Səhifələrdə axtarın...",
    alPrint: "✓ Çap əmri göndərildi. Astara sərhəd gömrük printeri ilə əlaqə quruldu.",
    alSuccess: "✓ Uğurlu! Qablaşdırma spesifikasiyası verilənləri və ixrac broşürası bu ünvana göndərildi: ",
    dismissBtn: "BAĞLA",
    pages: {
      p1: {
        title: "Qapaq və Texniki Giriş",
        subtitle: "GilaFruit ümumi topdansatış kalibrləri və qablaşdırma bələdçisi",
        prefaceTitle: "SABZ GOSTARAN GILAN FRUIT CO.",
        docRef: "SƏNƏD KODU: GF-EXP-2026-V3.4 • XƏZƏRYANI BÖLGƏ İXRACATI",
        dear: "Dəyərli Tərəfdaşlarımız və Logistika Menecerlərimiz,",
        para1: "GilaFruit olaraq beynəlxalq standartlara tam uyğun meyvə-tərəvəzlərimizin rəsmi kataloqunu təqdim etməkdən məmnunluq duyuruq. Talesh və Astara qablaşdırma xətlərimiz idxalçılara təzə bəhrələr çatdırır.",
        para2: "Bu kitabda daşıma və saxlama dövrlərində məhsulların keyfiyyətli qalması üçün lazım gələn temperatur, nəmlik və etilen qaydaları toplanmışdır."
      }
    }
  },
  uk: {
    b2bTag: "B2B Торгові Бюлетені",
    title: "Експортний каталог 2026",
    subtitle: "Ознайомтеся онлайн або завантажте технічний каталог, що містить хімічні індекси, вагові параметри тари та розміри упаковок.",
    insideHeader: "Що всередині каталогу GilaFruit?",
    insideDesc: "Наш каталог розроблений для імпортерів та фахівців міжнародної логістики з метою перевірки стандартів калібрування.",
    bullet1: "Специфікації калібрування ківі Hayward.",
    bullet2: "Аналіз сушіння часнику в Гілані.",
    bullet3: "Параметри міцності кавунів Charleston Gray.",
    bullet4: "Допуски розмірів гофрокоробів та ящиків.",
    bullet5: "Нормативи щодо очищення етилену на складах.",
    downloadTitle: "Завантажити цифровий PDF",
    downloadDesc: "Введіть корпоративний email, щоб отримати повний каталог безпосередньо.",
    emailInputLabel: "Робочий корпоративний Email",
    submitBtnDefault: "Отримати PDF",
    submitBtnDownloading: "Підготовка...",
    downloadConsent: "Завантажуючи, ви погоджуєтеся на щотижневе оновлення прайс-листів.",
    filenameLabel: "GilaFruit_Wholesale_Export_Catalog_2026.pdf",
    fileSizeLabel: "Розмір: 4.8 МБ • Сторінок: 5",
    embedPdfTab: "Інтерактивний PDF",
    simulatedSheetTab: "Цифровий перегляд сторінок",
    embedHeading: "ПЕРЕГЛЯД ДОКУМЕНТІВ В БРАУЗЕРІ",
    embedSubheading: "Доступне пряме посилання на PDF",
    quickPageGuideLabel: "Перегляд:",
    quickPageGuideDesc: "Використовуйте мініатюри для перемикання сторінок",
    catalogPagesHeading: "Сторінки каталогу",
    confidentialLabel: "КОНФІДЕНЦІЙНИЙ ДОКУМЕНТ",
    contactFooter: "Відділ експорту Астара: +98 21 9109 9091",
    zoomLabel: "Масштаб",
    pageLabel: "Сторінка",
    searchPagesPlaceholder: "Пошук по сторінках...",
    alPrint: "✓ Друк запущено. З'єднання зі складським принтером Астари встановлено.",
    alSuccess: "✓ Готово! Експортну книгу відправлено на пошту: ",
    dismissBtn: "ЗАКРИТИ",
    pages: {
      p1: {
        title: "Обкладинка та введення",
        subtitle: "Загальні вагові індекси та нормативи упаковки GilaFruit",
        prefaceTitle: "SABZ GOSTARAN GILAN FRUIT CO.",
        docRef: "DOC REF: GF-EXP-2026-V3.4 • CASPIAN EXPORTS",
        dear: "Шановні партнери та логісти,",
        para1: "GilaFruit рада представити технічний класифікатор для закупівлі якісних свіжих товарів з Ірану. Понад 24 роки наші склади в Астарі та Талеші працюють за європейськими регламентами.",
        para2: "Каталог містить вагові пропорції калібрів, криву вологості та температури для надійного перевезення."
      }
    }
  }
};
