export const DETAIL_TEXTS: Record<string, Record<string, string>> = {
  en: {
    backToDirectory: "Back to Directory",
    varietyStandard: "Variety Standard",
    calibratedWeight: "Calibrated Weight",
    flavorProfile: "Flavor Profile",
    naturalColorTone: "Natural Color Tone",
    coreDimensions: "Core Dimensions",
    brixSugarIndex: "Brix Sugar Index",
    bulkPackingStyle: "Bulk Packing Style",
    hsCustomsCode: "HS Customs Code",
    geographicalOrigin: "Geographical Origin",
    exportSeason: "Export Season",
    primaryBatch: "★ PRIMARY BATCH",
    reeferStability: "⚡ HIGH REEFER STABILITY",
    sourcedInGilan: "🍀 100% SOURCED IN GILAN",
    datasheetTitle: "Crop Specifications Datasheet (Offline Ref)",
    exportGrade: "EXPORT GRADE A+",
    customRegulations: "Export custom regulations dictate transit clearances. Hover for details inside local documentation desk.",
    consultDesk: "Consult Our Export Desk 🟢",
    fastResponse: "Fast response in less than 5 minutes",
    yourName: "Your Name *",
    whatsappMobile: "Your WhatsApp Mobile *",
    yourEmail: "Your Email *",
    representativesContactNotice: "⚠️ Our English, Russian, and Persian trade representatives will contact you directly with calculated load factors.",
    calculateFob: "Calculate & Message FOB",
    processing: "Processing...",
    estimatesLoaded: "Estimates Loaded!",
    estimatesLoadedDesc: "We have processed your cargo metric tonnage and compiled the exact shipping factors. You can open the direct sales conversation with our representatives right here:",
    openSalesDesk: "Open Sales Desk",
    productNotFound: "Product Not Found",
    productNotFoundDesc: "The agricultural category or specific product does not exist or has been modified.",
    returnToDirectory: "Return to directory",
    tonnageCalculator: "INTERACTIVE FREIGHT CAPACITY ESTIMATION",
    metricTonnage: "Desired Metric Tonnage:",
    calcEstimates: "Real-time logistics estimates calculated automatically based on gross weights.",
    tempParam: "Core Temperature Parameters",
    humidityLevel: "Ambient Relative Humidity Level",
    preCoolingProtocol: "Pre-cooling Hydro-treatment Protocol",
    maxDuration: "Estimated Shelf-life Limit",
    freshExchange: "Required Reefers Fresh Air Exchange",
    packagingWeight: "Individual Standard Box Weight",
    reeferCap: "Custom Reefer Truck Capacity Index",
    cargoHandling: "Cargo Handling Special Instructions",
    // New Sections
    coldChainScheme: "● COLD-CHAIN PROTECTION SCHEME",
    coldChainTitle: "Meticulous Farm-to-Pallet Refrigerated Process",
    coldChainDesc: "We monitor atmospheric metrics from deep Caspian orchard plots to final customs checks. All GilaFruit dispatches are tracked through the following state-of-the-art staging flow:",
    stage01Title: "Pre-cooling Hydro-treatment",
    stage01Desc: "Pulp core temperature is dropped within 4 hours using water refrigeration grids to halt natural sugar degradation.",
    stage02Title: "Optical Sorting & Gravity calibration",
    stage02Desc: "Dual-lens digital calibrators assess external shell integrity, exact caliber thickness, and color blemishes.",
    stage03Title: "Nitrogen Flushing Packing",
    stage03Desc: "Ventilated custom corrugated boards are packed with ethylene scavenging absorbers, locking absolute crispness.",
    stage04Title: "Sealed RF Transit Crossing",
    stage04Desc: "Refrigerated trucks maintain consistent telemetry data parameters from Gilan depots to final delivery terminals.",
    stepByStepPrep: "⚙️ STEP-BY-STEP PREPARATION",
    prodPackingProcess: "Production and Packaging Process",
    prodPackingDesc: "Our meticulous production process ensures the freshness and quality of our {product}. After harvest, the {product} undergoes a rigorous sorting and cleaning process. We package the fresh {product} in Iran in hygienic, standard packaging matching target market needs.",
    complianceSafety: "🛡️ COMPLIANCE & SAFETY STAMP",
    qualitySafetyTitle: "Quality and Product Safety Guarantee",
    qualitySafetyDesc: "At GILAFRUIT, we prioritize product quality and customer satisfaction. Our experts supervise all stages of {product} production and packaging, guaranteeing a superior quality, taste, and safety with certificates.",
    facilityWalkthrough: "FACILITY WALKTHROUGH",
    liveFootageTitle: "Gilan Sorting House Live footage",
    sortingFacility: "Sorting facility",
    videoLength: "📹 Plant Sorting center - 2:14 min",
    loadingVideoStream: "Loading video stream from Astara warehouse...",
    closePlayback: "Close Playback",
    faqHeader: "FREQUENTLY ASKED INQUIRIES",
    faqTitle: "Global Procurement Instructions",
    secureSupplies: "🌟 SECURE WHOLESALE SUPPLIES DIRECT FROM ORCHARD",
    whyInternational: "Why International Buyers Select GilaFruit",
    volSupplyTitle: "Regular Heavy Volumes Supply",
    volSupplyDesc: "Owning massive kiwi groves in Astara and Talesh allows us to process and execute up to 2,000 metric tons per campaign safely.",
    coldWarehousingTitle: "Advanced Controlled Cold Warehouses",
    coldWarehousingDesc: "Our facilities monitor and filter ethylene build-up and calibrate relative humidity to prevent damage during transit.",
    customsTransitTitle: "Customs Transit Seals Pre-Clearance",
    customsTransitDesc: "Our customs division expedites phytosanitary certificates, EAEU declaration filing, and stamps directly at Astara port.",
    packingPricingTitle: "Competitive Packing-House Pricing",
    packingPricingDesc: "By controlling harvesting, sorting, boxing, and shipping fleet, we exclude secondary brokers completely.",
    strategicAdvantages: "🚀 Strategic Advantages",
    advantagesOfCompany: "Advantages of Buying from Our Company",
    advantagesIntro: "As Iranian agriculture grows global, Gilafruit delivers unmatched value proposition for high-volume wholesale {product}:",
    adv1Title: "High-volume supply",
    adv1Desc: "Due to long-term contracts with farmers, we are able to supply large volumes of fresh {product} from Iran with consistent quality.",
    adv2Title: "Variety of types",
    adv2Desc: "We offer various types of Iranian {product} with different flavor and size characteristics, matching your market demands.",
    adv3Title: "Custom packaging",
    adv3Desc: "Product packaging is carried out based on customer requests, ensuring your fresh food arrives in optimal condition.",
    adv4Title: "Fast shipping",
    adv4Desc: "We use the best transport methods to deliver goods rapidly while keeping high quality.",
    adv5Title: "Competitive price",
    adv5Desc: "By eliminating intermediaries and utilizing optimal methods, we offer the best direct price of Iranian {product}.",
    exportDestinations: "🌍 Export Destinations",
    targetMarkets: "Target Markets",
    targetMarketsDesc: "Due to its high quality, {product} Iran has garnered significant interest. Gilafruit exports to Russia, Belarus, Azerbaijan, Georgia, Armenia, Turkey, and Persian Gulf countries.",
    mktRussia: "Russia",
    mktBelarus: "Belarus",
    mktAzerbaijan: "Azerbaijan",
    mktGeorgia: "Georgia",
    mktArmenia: "Armenia",
    mktTurkey: "Turkey",
    mktPersianGulf: "Persian Gulf",
    connectWithSales: "📞 CONNECT WITH SALES",
    contactUsTitle: "Contact Us",
    contactUsDesc: "Contact GilaFruit sales experts via WhatsApp and email for pricing, advice, and detailed wholesale load logistics.",
    whatsappHelp: "WhatsApp Assistance",
    industrialExcellence: "📷 INDUSTRIAL EXCELLENCE IMAGES",
    galleryDetailsTitle: "Caspian Sorting House & Packing Facility",
    galleryDetailsDesc: "Visual tour inside our northern sorting and packaging facility showing our quality control steps:",
    step01Title: "Hygienic Packaging Baskets",
    step01Desc: "Sized plastic baskets catering to international transit guidelines.",
    step02Title: "Fresh Selection",
    step02Desc: "Rigorous manual sorting of high-quality Iranian agricultural bulbs.",
    step03Title: "Premium Grade Classification",
    step03Desc: "Graded and standardized for export-compliant global markets.",
    step04Title: "Ventilated Basket Stacking",
    step04Desc: "Strategically stacked for optimal continuous airflow inside reefers.",
    step05Title: "Iran Sorting Units",
    step05Desc: "Supervised by experienced experts to guarantee superior quality.",
    step06Title: "Cleaned Dried Bulk",
    step06Desc: "Moisture-minimized bulbs prepared for long distance Eurasian dispatch channels.",
    clickToPreview: "CLICK TO PREVIEW",
    reviewBoard: "WHOLESALE COMMUNITY BOARD",
    reviewTitle: "Verified Agent Forum & Trade Inquiries",
    reviewDesc: "Connect with or read statements from international procurement bureaus and export managers currently importing premium GilaFruit lines.",
    verifiedAgent: "Verified Agent",
    registeredDispatch: "Registered Dispatch Date",
    helpful: "Helpful?",
    secureTimeline: "SECURE TIMELINE SUBMISSION",
    submitTrade: "Submit Trade Statement",
    submitTradeDesc: "Provide feedback regarding transit quality, grading, or dock reception. Fields marked with asterisk (*) are required.",
    productEvaluation: "Product Evaluation *",
    outOfStars: "out of 5 Stars",
    displayName: "Your Display Name *",
    tradeEmail: "Working Trade Email *",
    wholesaleStatement: "Public Wholesale Statement *",
    statementPlaceholder: "Describe GilaFruit delivery transit speed, packhouse grading accuracy, or specify your active procurement requirements...",
    notRobot: "I'm not a robot",
    postStatement: "Post Crop Statement",
    cargoSuccess: "Cargo statement registered! Your feedback will show after auto-verification."
  },
  fa: {
    backToDirectory: "بازگشت به کاتالوگ محصولات",
    varietyStandard: "نوع و رقم استاندارد",
    calibratedWeight: "وزن کالیبره‌شده تاییدشده",
    flavorProfile: "طعم و عطر طبیعی",
    naturalColorTone: "رنگ طبیعی بارگیری شده",
    coreDimensions: "ابعاد و اندازه و ضخامت",
    brixSugarIndex: "میزان قند طبیعی (بریکس)",
    bulkPackingStyle: "نحوه چیدمان و بسته‌بندی عمده",
    hsCustomsCode: "کد تعرفه ترخیص گمرکی (HS)",
    geographicalOrigin: "منطقه جغرافیایی و باغات مبدا",
    exportSeason: "فصل برداشت و صادرات فعال",
    primaryBatch: "★ محموله درجه یک صادراتی",
    reeferStability: "⚡ پایداری انتقال در کانتینر یخچال‌دار",
    sourcedInGilan: "🍀 تامین ۱۰۰٪ از باغات ممتاز گیلان",
    datasheetTitle: "دیتاشیت مشخصات فنی محموله صادراتی",
    exportGrade: "گرید صادرات درجه اول ممتاز +A",
    customRegulations: "مقررات گمرکی و بهداشتی ترانزیت کالا در مرز خروجی اعمال خواهد شد.",
    consultDesk: "مشاوره تخصصی با میز صادرات و فروش 🟢",
    fastResponse: "پاسخ تجاری سریع در کمتر از ۵ دقیقه",
    yourName: "نام و نام خانوادگی شما *",
    whatsappMobile: "شماره موبایل واتس‌اپ فعال شما *",
    yourEmail: "آدرس ایمیل کاری شما *",
    representativesContactNotice: "⚠️ نمایندگان فروش ما به زبان‌های روسی، فارسی و انگلیسی مستقیماً جهت جزئیات فاکتور با شما تماس خواهند گرفت.",
    calculateFob: "محاسبه قیمت و استعلام FOB",
    processing: "در حال پردازش...",
    estimatesLoaded: "برآورد بارگیری و کانتینر انجام شد!",
    estimatesLoadedDesc: "ما بر اساس ظرفیت درخواستی شما متراژ بارگیری و وزن تناژ خالص رفرنس کانتینری را محاسبه کردیم. اکنون می‌توانید گفتگوی زنده با تیم فروش را آغاز کنید:",
    openSalesDesk: "باز کردن پیام مستقیم واتس‌اپ واحد فروش",
    productNotFound: "محصول مورد نظر یافت نشد",
    productNotFoundDesc: "دسته یا تنوع محصول درخواستی در لیست کاتالوگ فعلی بارگذاری نشده است.",
    returnToDirectory: "بازگشت به فهرست محصولات صادراتی",
    tonnageCalculator: "محاسبه‌گر تعاملی ظرفیت بارگیری و برآوردهای لجستیک",
    metricTonnage: "تناژ درخواستی شما (به تن):",
    calcEstimates: "برآوردهای لجستیکی برای حمل و کرایه بر اساس وزن خالص کانتینرها محاسبه شد.",
    tempParam: "دمای داخلی کانتینر جهت حفظ کیفیت بار",
    humidityLevel: "رطوبت نسبی هوای کانتینر در حمل و نقل",
    preCoolingProtocol: "پروتکل هیدروکولینگ و پیش‌سرمایش سریع بار",
    maxDuration: "مدت زمان نگهداری باکیفیت و طول عمر بار",
    freshExchange: "میزان تهویه هوای کانتینر یخچالی",
    packagingWeight: "وزن خالص هر کارتن یا جعبه بسته‌بندی",
    reeferCap: "ظرفیت کانتینر یخچالی تریلر استاندارد",
    cargoHandling: "دستورالعمل ویژه حمل و نگهداری جهت حفظ تازگی کالا",
    // New Sections
    coldChainScheme: "● طرح حفاظت زنجیره سرد غلات و تره‌بار",
    coldChainTitle: "فرآیند دقیق سرمایشی و مبرد از باغ تا پالت",
    coldChainDesc: "ما شاخص‌های جوی را از باغ‌های سرسبز خزر تا آخرین مراحل ترخیص گمرکی نظارت می‌کنیم. تمام محموله‌ها از طریق فرآیند مدرن زیر ردیابی می‌شوند:",
    stage01Title: "پیش‌سرمایش هیدرو-ترتیمنت",
    stage01Desc: "دمای هسته محصول ظرف ۴ ساعت با استفاده از سیستم‌های سرمایش آب کاهش می‌یابد تا از تجزیه قند طبیعی جلوگیری شود.",
    stage02Title: "سورتینگ نوری و کالیبراسیون جاذبه",
    stage02Desc: "دستگاه‌های کالیبراتور دیجیتال دو لنز، سلامت پوسته، ضخامت کالیبر و عیوب رنگ را ارزیابی می‌کنند.",
    stage03Title: "بسته‌بندی با گاز خنثی نیتروژن",
    stage03Desc: "کارتن‌های دوجداره با جاذب‌های اتیلن پر می‌شوند تا پایداری و تازگی مطلق بار حفظ شود.",
    stage04Title: "حمل و ترانزیت یخچالی پلمب شده",
    stage04Desc: "کامیون‌های یخچال‌دار داده‌های دما را از سردخانه‌های شمالی تا پایانه‌های تحویل نهایی مانیتور می‌کنند.",
    stepByStepPrep: "⚙️ مراحل آماده‌سازی و فرآوری",
    prodPackingProcess: "فرآیند تولید و بسته‌بندی محصول صادراتی",
    prodPackingDesc: "فرآیند آماده‌سازی دقیق ما طراوت و کیفیت {product} را تضمین می‌کند. پس از برداشت، {product} تحت فرآیند درجه‌بندی و شستشوی استاندارد قرار می‌گیرد و با رعایت پروتکل‌های بهداشتی بسته‌بندی می‌شود.",
    complianceSafety: "🛡️ انطباق، استانداردها و تاییدیه سلامت",
    qualitySafetyTitle: "تعدیل کیفیت و تاییدیه سلامت کالا",
    qualitySafetyDesc: "ما در گیلافروت بر کیفیت عالی محصول تکیه داریم. کارشناسان ما تمامی مراحل آماده‌سازی {product} را به دقت مانیتور می‌کنند تا سلامت و گواهینامه‌های رسمی آن تضمین شود.",
    facilityWalkthrough: "تور مجازی مجموعه سورتینگ و سردخانه",
    liveFootageTitle: "مجموعه سورتینگ گیلافروت؛ فیلم زنده کارخانه",
    sortingFacility: "واحد سورت و بسته‌بندی",
    videoLength: "📹 ویدیو خط سورتینگ گیلان - ۲:۱۴ دقیقه",
    loadingVideoStream: "درحال بارگذاری جریان ویدیویی از سردخانه لبه مرز...",
    closePlayback: "بستن پخش ویدیو",
    faqHeader: "سوالات متداول تجاری",
    faqTitle: "دستورالعمل‌ها و راهنمای خرید و ترخیص بین‌المللی",
    secureSupplies: "🌟 تامین مستقیم بار عمده از باغات ممتاز شمال",
    whyInternational: "چرا خریداران بین‌المللی گیلافروت را انتخاب می‌کنند؟",
    volSupplyTitle: "تامین تناژ بالا به صورت منظم هفتگی",
    volSupplyDesc: "مالکیت باغات ممتاز تالش و آستارا به همراه شبکه گسترده باغداران محلی توان تامین دائم تا ۲۰۰۰ تن را به ما می‌دهد.",
    coldWarehousingTitle: "انبارها و سردخانه‌های مدرن کنترل گاز اتیلن",
    coldWarehousingDesc: "سردخانه‌های ما گاز اтиلن مازاد را به طور پیوسته مانیتور کرده و فیلتر می‌کنند تا از آسیب‌ها پیشگیری شود.",
    customsTransitTitle: "تسهیل و پلمب گمرکی در مبدا گیلان",
    customsTransitDesc: "بخش گمرکی اختصاصی امور بهداشت بذر و نبات، مانیفست حمل و ثبت اوراسیا را یکپارچه پیش می‌برد.",
    packingPricingTitle: "قیمت‌گذاری دست اول درب سردخانه",
    packingPricingDesc: "با اداره کامل برداشت، سورتینگ اتوماتیک، جعبه‌سازی و ناوگان لجستیک، واسطه‌ها را کاملاً حذف کرده‌ایم.",
    strategicAdvantages: "🚀 مزایای استراتژیک کمپانی",
    advantagesOfCompany: "مزایای برتر همکاری و صادرات",
    advantagesIntro: "گیلافروت ارزش برتری را برای خریداران عمده و حجم‌های سنگین {product} پیشنهاد می‌دهد:",
    adv1Title: "تامین دائم بار غول‌پیکر",
    adv1Desc: "به لطف قرارداد مستقیم با کشاورزان، در تمام فصول سال تداوم حجم بارهای لوکس {product} تضمین شده است.",
    adv2Title: "ارقام متنوع و کالیبر درخواستی",
    adv2Desc: "پیشنهاد انواع {product} ممتاز با ویژگی‌ها و کالیبرهای مختلف متناسب با بازارهای اروپائی یا خلیجی.",
    adv3Title: "بسته‌بندی دلخواه مشتری",
    adv3Desc: "شخصی‌سازی کارتن و جعبه به درخواست خریدار، برای رسیدن بار به مقصدهای دورافتاده به بهترین حالت ممکن.",
    adv4Title: "حمل و نقل فوق‌العاده سریع یخچالی",
    adv4Desc: "استفاده از سریع‌ترین جاده‌های ترانزیتی و ناوگان‌های نوساز جهت تحویل تازه و باطراوت بار.",
    adv5Title: "کمترین قیمت تمام شده در ایران",
    adv5Desc: "ارائه نرخ حاشیه سود بالا به واسطه حذف دلالان، قیمت دست اول واقعی {product} ایرانی.",
    exportDestinations: "🌍 مقاصد ترانزیت صادراتی فعال",
    targetMarkets: "بازارهای هدف و صادرات",
    targetMarketsDesc: "محصولات ممتاز {product} ما در سطح منطقه نظیر روسیه، بلاروس، آذربایجان، گرجستان، ارمنستان، ترکیه و خلیج فارس تقاضای بالایی دارند.",
    mktRussia: "روسیه",
    mktBelarus: "بلاروس",
    mktAzerbaijan: "آذربایجان",
    mktGeorgia: "گرجستان",
    mktArmenia: "ارمنستان",
    mktTurkey: "ترکیه",
    mktPersianGulf: "کشورهای عربی خلیج فارس",
    connectWithSales: "📞 ارتباط سریع با میز فروش و صادرات",
    contactUsTitle: "تماس با ما",
    contactUsDesc: "جهت مطلع شدن از آخرین قیمت صادراتی {product} و هماهنگی تریلرها با کارشناسان ما مستقیماً گفتگو کنید.",
    whatsappHelp: "پاسخگویی سریع واتس‌اپ",
    industrialExcellence: "📷 تصاویر مستند مجموعه صادراتی و آماده‌سازی",
    galleryDetailsTitle: "مرکز کنترل کیفی، سورتینگ و پالتایزینگ گیلان",
    galleryDetailsDesc: "گشتی کوتاه در مجهزترین کارخانه تصفیه و بوجاری ترانزیتی شمال ایران:",
    step01Title: "سبدهای آنتی‌یووی بسته‌بندی صادراتی",
    step01Desc: "سبدهای پلاستیکی بهداشتی همرده با آخرین مقررات حمل فرادوربین.",
    step02Title: "سورتینگ دستی و پالایش غده‌ها",
    step02Desc: "غربالگری فیزیکی سریع کالا توسط کادر باسابقه جهت دفع عیوب اولیه.",
    step03Title: "کلاسیفیکاسیون و جداسازی سایز برتر",
    step03Desc: "درجه‌بندی استاندارد کالیبر دابل لایه برای عرضه به برترین هایپرمارکت‌های بین‌المللی.",
    step04Title: "چیدمان و پین دوجداره پالت باد خور",
    step04Desc: "آرایش چیدمان ستونی جعبه‌ها در پالت برای ایجاد حداکثر جریان باد مبرد در تریلی.",
    step05Title: "خط اتوماتیک اسکن نوری مرغوبیت",
    step05Desc: "بررسی تمام ابعاد توسط ماشین‌آلات نوین جهت دفع بافت سست و چروکیده.",
    step06Title: "خشک‌سازی نهایی و رفع رطوبت ترانزیت",
    step06Desc: "رفع نم بار جهت مقابله جدی با ایجاد هاگ یا کپک در طی ترانزیت طولانی اوراسیایی.",
    clickToPreview: "مشاهده عکس باکیفیت بالا",
    reviewBoard: "تالار تایید نظرات و اظهارات تجاری بازرگانان",
    reviewTitle: "دیدگاه‌های بازرسان و کارگزاران گمرکی",
    reviewDesc: "اظهار نظرهای بازرگانان عمده کشورهای خریدار در خصوص کیفیت بار و سرعت ترخیص مدارک در پایانه ها را مطالعه کنید.",
    verifiedAgent: "بازرگان تایید شده",
    registeredDispatch: "تاریخ ثبت ترخیص و حمل گمرکی",
    helpful: "آیا این نظر مفید بود؟",
    secureTimeline: "ثبت بازخورد بازرگانی و تجاری",
    submitTrade: "ارسال بیانیه و گزارش ترانزیت کالا",
    submitTradeDesc: "فرم ارزیابی کیفیت، نحوه ترخیص گمرکی و حمل و بارگیری کالا را تکمیل نمائید. فیلدهای ستاره دار الزامی است.",
    productEvaluation: "ارزیابی کیفیت محصول *",
    outOfStars: "ستاره از ۵ سطح عالی کیفیت",
    displayName: "نام کامل نماینده تجاری *",
    tradeEmail: "ایمیل کاری معتبر خریدار *",
    wholesaleStatement: "بیانیه و ارزیابی صادراتی شما *",
    statementPlaceholder: "کیفیت کالیبراسیون، سلامت بار حین رسیدن به مرز خروجی و ارزیابی لجستیک را بیان کنید...",
    notRobot: "من ربات نیستм",
    postStatement: "ثبت و تایید نهایی بیانیه بار",
    cargoSuccess: "گزارش با موفقیت برای نمایش در گالری ثبت بازرگانی فرستاده شد."
  },
  ru: {
    backToDirectory: "Назад в каталог",
    varietyStandard: "Сортовой стандарт",
    calibratedWeight: "Калиброванный вес",
    flavorProfile: "Аромат и вкус",
    naturalColorTone: "Естественный оттенок",
    coreDimensions: "Габариты калибра",
    brixSugarIndex: "Показатель сахара (Брикс)",
    bulkPackingStyle: "Оптовая упаковка",
    hsCustomsCode: "Код ТН ВЭД",
    geographicalOrigin: "Происхождение",
    exportSeason: "Сезон экспорта",
    primaryBatch: "★ ПЕРВИЧНАЯ ПАРТИЯ",
    reeferStability: "⚡ ВЫСОКАЯ СТАБИЛЬНОСТЬ В РЕФЕ",
    sourcedInGilan: "🍀 100% СОБРАНО В ГИЛАНЕ",
    datasheetTitle: "Спецификация экспортного груза",
    exportGrade: "ЭКСПОРТНЫЙ СОРТ А+",
    customRegulations: "Таможенные правила диктуют нормы транзита.",
    consultDesk: "Получить коммерческое предложение 🟢",
    fastResponse: "Быстрый ответ в течение 5 минут",
    yourName: "Ваше имя *",
    whatsappMobile: "Ваш WhatsApp мобильный *",
    yourEmail: "Ваш Email *",
    representativesContactNotice: "⚠️ Наши представители свяжутся с вами на русском, английском или персидском языке.",
    calculateFob: "Рассчитать и отправить FOB",
    processing: "Обработка...",
    estimatesLoaded: "Расчеты составлены!",
    estimatesLoadedDesc: "Мы проанализировали параметры вашего груза и рассчитали точные факторы транспортировки. Вы можете связаться с нами напрямую:",
    openSalesDesk: "Открыть чат продаж",
    productNotFound: "Товар не найден",
    productNotFoundDesc: "Такой продукт отсутствует в нашей текущей сельскохозяйственной номенклатуре.",
    returnToDirectory: "Вернуться в каталог",
    tonnageCalculator: "ИНТЕРАКТИВНЫЙ РАСЧЕТ ЛОГИСТИКИ",
    metricTonnage: "Желаемый тоннаж (в тоннах):",
    calcEstimates: "Автоматический расчет логистических спецификаций груза по брутто-весу.",
    tempParam: "Режим температуры мякоти",
    humidityLevel: "Относительная влажность рефрижератора",
    preCoolingProtocol: "Протокол предварительного охлаждения",
    maxDuration: "Срок хранения при соблюдении холодовой цепи",
    freshExchange: "Необходимый приток свежего воздуха куба в час",
    packagingWeight: "Вес стандартной коробки упаковки",
    reeferCap: "Вместимость стандартного рефрижератора",
    cargoHandling: "Особые инструкции к хранению и перевозке",
    // New Sections
    coldChainScheme: "● СХЕМА ХОЛОДОВОЙ ЦЕПИ",
    coldChainTitle: "Процесс охлаждения от поля до паллеты",
    coldChainDesc: "Мы контролируем атмосферные показатели от глубоких каспийских плантаций до таможни. Все отправки GilaFruit отслеживаются:",
    stage01Title: "Гидро-охлаждение",
    stage01Desc: "Температура мякоти снижается в течение 4 часов для прекращения распада естественного сахара.",
    stage02Title: "Оптическая сортировка",
    stage02Desc: "Двухобъективные цифровые калибраторы оценивают форму, калибр плода и отсутствие дефектов цвета.",
    stage03Title: "Упаковка с азотом",
    stage03Desc: "Вентилируемый картон наполняется этиленовыми поглотителями для длительного сохранения свежести.",
    stage04Title: "Герметичный рефрижератор",
    stage04Desc: "Мы сохраняем точные температурные телеметрические данные от складов Гилана до терминалов доставки.",
    stepByStepPrep: "⚙️ ПОШАГОВАЯ ПОДГОТОВКА",
    prodPackingProcess: "Процесс производства и упаковки",
    prodPackingDesc: "Наш производственный процесс гарантирует свежесть {product}. После сбора урожая {product} тщательно сортируется, очищается и упаковывается.",
    complianceSafety: "🛡️ БЕЗОПАСНОСТЬ И СТАНДАРТЫ",
    qualitySafetyTitle: "Гарантия соответствия качества",
    qualitySafetyDesc: "В GILAFRUIT мы ставим качество во главу угла. Наши эксперты контролируют все фазы упаковки {product}, предоставляя международные фитосанитарные сертификаты.",
    facilityWalkthrough: "ЭКСКУРСИЯ ПО ОБЪЕКТУ",
    liveFootageTitle: "Сортировочный цех Гилана вживую",
    sortingFacility: "Сортировочный комплекс",
    videoLength: "📹 Видео со склада - 2:14 мин",
    loadingVideoStream: "Загрузка видеопотока со склада в Астаре...",
    closePlayback: "Закрыть плеер",
    faqHeader: "ЧАСТО ЗАДАВАЕМЫЕ ВОПРОСЫ",
    faqTitle: "Инструкция к закупке",
    secureSupplies: "🌟 ОПТОВЫЕ ПОСТАВКИ НАПРЯМУЮ ИЗ САДОВ",
    whyInternational: "Почему импортеры выбирают GilaFruit",
    volSupplyTitle: "Регулярный крупный объем",
    volSupplyDesc: "Собственные плантации киви в Астаре и Талеше позволяют поставлять до 2000 тонн качественного товара за сезон.",
    coldWarehousingTitle: "Современные склады с контролем этилена",
    coldWarehousingDesc: "Склады оборудованы фильтрами этилена и калибровочными контроллерами влажности для избежания порчи структуры.",
    customsTransitTitle: "Быстрое таможенное оформление",
    customsTransitDesc: "Наш таможенный отдел оформляет фитосанитарные сертификаты и декларации ЕАС прямо на границе в Астаре.",
    packingPricingTitle: "Лучшие цены за счет самообеспечения",
    packingPricingDesc: "Мы сами собираем, калибруем, упаковываем и перевозим грузы, полностью исключая наценку посредников.",
    strategicAdvantages: "🚀 Стратегические преимущества",
    advantagesOfCompany: "Преимущества закупки у нас",
    advantagesIntro: "Наши предложения по крупнооптовым поставкам лучшего {product} из Ирана основываются на следующих факторах:",
    adv1Title: "Высокие объемы",
    adv1Desc: "Долгосрочные договоры с хозяйствами обеспечивают постоянный поток свежего {product} стабильного отбора.",
    adv2Title: "Разнообразие сортов",
    adv2Desc: "Предлагаем разные сорта {product} с уникальными характеристиками сладости и размеров под ваш рынок.",
    adv3Title: "Индивидуальный короб",
    adv3Desc: "Дизайн и структура тары согласуются с требованиями заказчика для долгосрочного транзита.",
    adv4Title: "Надежные рефрижераторы",
    adv4Desc: "Используются новые тягачи с самописцами температуры, минимизируя порчу сырья.",
    adv5Title: "Качественная цена",
    adv5Desc: "За счет автоматизации производства и отсутствия перекупщиков мы даем самую низкую оптовую цену в СНГ на {product}.",
    exportDestinations: "🌍 Направления экспорта",
    targetMarkets: "Рынки сбыта",
    targetMarketsDesc: "{product} из Ирана пользуется огромным спросом в России, Беларуси, Азербайджане, Армении, Турции и странах Персидского залива.",
    mktRussia: "Россия",
    mktBelarus: "Беларусь",
    mktAzerbaijan: "Азербайджан",
    mktGeorgia: "Грузия",
    mktArmenia: "Армения",
    mktTurkey: "Турция",
    mktPersianGulf: "Страны Залива",
    connectWithSales: "📞 СВЯЗЬ С ОТДЕЛОМ ПРОДАЖ",
    contactUsTitle: "Обратная связь",
    contactUsDesc: "Свяжитесь с менеджерами GilaFruit для запроса прайс-листов и бронирования холодильных автопоездов.",
    whatsappHelp: "Чат поддержки в WhatsApp",
    industrialExcellence: "📷 ЭКСКЛЮЗИВНЫЕ КАДРЫ С ПРОИЗВОДСТВА",
    galleryDetailsTitle: "Упаковочно-сортировочный комплекс",
    galleryDetailsDesc: "Фотографии этапов калибровки, укладки и очистки грузов перед отправкой:",
    step01Title: "Санитарные ящики упаковки",
    step01Desc: "Ударопрочные пластиковые лотки под строгие транзитные нормы ЕАС.",
    step02Title: "Ручной отбор сырья",
    step02Desc: "Первичный ручной осмотр плодов опытными сортировщиками.",
    step03Title: "Калибровка премиум класса",
    step03Desc: "Точная уортировка размеров плодов под международные нормы экспорта.",
    step04Title: "Умное складирование паллет",
    step04Desc: "Укладка коробов с обеспечением идеальной циркуляции воздуха.",
    step05Title: "Контроль оптическими датчиками",
    step05Desc: "Высокоточная механическая очистка от поврежденных экземпляров.",
    step06Title: "Сухой режим подготовки",
    step06Desc: "Контроль и подавление излишней влажности перед дальними рейсами в РФ.",
    clickToPreview: "ПОКАЗАТЬ КАРТИНКУ",
    reviewBoard: "ПОРТАЛ ОТЗЫВОВ И ЗАКУПОК",
    reviewTitle: "Верифицированные отзывы импортеров",
    reviewDesc: "Мнения представителей торговых сетей и дистрибьюторов, оценивших качество услуг GilaFruit.",
    verifiedAgent: "Верифицированный представитель",
    registeredDispatch: "Дата оформления грузовой таможенной декларации",
    helpful: "Полезно? ",
    secureTimeline: "БЕЗОПАСНАЯ ОТПРАВКА СВЕДЕНИЙ",
    submitTrade: "Добавить отзыв по сделке",
    submitTradeDesc: "Поделитесь впечатлением от сортности, плотности калибра и прохождения границы. Все поля со звездочкой обязательны.",
    productEvaluation: "Оценка товара *",
    outOfStars: "из 5 звезд",
    displayName: "Ваше Имя / Название Компании *",
    tradeEmail: "Ваш рабочий Корпоративный Email *",
    wholesaleStatement: "Публичное мнение по грузу *",
    statementPlaceholder: "Какие плюсы вы увидели в сортности, как прибыла рефсекция, качество обслуживания...",
    notRobot: "Я не робот",
    postStatement: "Опубликовать отзыв",
    cargoSuccess: "Отзыв принят и будет опубликован сразу после автоматической спам-проверки."
  },
  ar: {
    backToDirectory: "العودة إلى دليل المنتجات",
    varietyStandard: "معيار الصنف والنوعيه",
    calibratedWeight: "الوزن المعاير الدقيق",
    flavorProfile: "النكهة والرائحة الطبيعية",
    naturalColorTone: "درجة اللون الطبيعي",
    coreDimensions: "الوزن والأبعاد القياسية",
    brixSugarIndex: "مؤشر نسبة السكر (بريكس)",
    bulkPackingStyle: "أسلوب التعبئة والتغليف بالجملة",
    hsCustomsCode: "الرمز والتعرفة الجمركية (HS)",
    geographicalOrigin: "المنشأ الجغرافي وبساتين الحصاد",
    exportSeason: "موسم التصدير الفعال الحالى",
    primaryBatch: "★ شحنة أولى ممتازة درجه أولى",
    reeferStability: "⚡ استقرار تبريد عالٍ أثناء الشحن",
    sourcedInGilan: "🍀 حصاد طبيعي مستورد من جيلان 100٪",
    datasheetTitle: "ورقة المواصفات الفنية للمحصول المصدر",
    exportGrade: "درجة تصدير فائقة الجودة +A",
    customRegulations: "تخضع الشحنات اللوجستية لقواعد وأنظمة الجمارك بالموانئ والمنافذ.",
    consultDesk: "استشر الإدارة التجارية مباشرة 🟢",
    fastResponse: "الرد التجاري السريع في أقل من 5 دقائق",
    yourName: "الاسم الكامل والصفة *",
    whatsappMobile: "رقم الواتساب بالرمز الدولي المباشر *",
    yourEmail: "عنوان بريدك الإلكتروني العملي *",
    representativesContactNotice: "⚠️ سيتصل بكم ممثلو المبيعات لدينا مباشرة باللغات الروسية أو العربية أو الفارسية لتنسيق مستندات النقل.",
    calculateFob: "احسب وطلب استعلام FOB",
    processing: "جاري حساب الأبعاد وتنسيق الشاحنة...",
    estimatesLoaded: "تم تجهيز تقديرات الحجم والوزن المطلوبة!",
    estimatesLoadedDesc: "لقد نجحنا في احتساب عوامل الشحن والتعبئة القياسية بناءً على الحجم المطلوب. يمكنك بدء محادثة واتساب فورية الآن:",
    openSalesDesk: "افتح نافذة المحادثة مباشرة مع وحدة المبيعات مع العرض المخصص",
    productNotFound: "المنتج غير متوفر بالكاتالوج حالياً",
    productNotFoundDesc: "مواصفات هذا الصنف أو المجموعة المطلوبة غير متوفرة بقاعدة البيانات الحالية.",
    returnToDirectory: "العودة لقائمة الأصناف الصالحة للتصدير",
    tonnageCalculator: "حاسبة تقدير القدرة اللوجستية وتوزيع الحاويات",
    metricTonnage: "الوزن الإجمالي المطلوب بالطن المتري:",
    calcEstimates: "تم حساب التقديرات بناءً على معايير الأوزان الإجمالية الإرشادية للشحن البري والبحري.",
    tempParam: "درجة الحرارة المطلوبة لقلب ثمار الشحنة لتعليق التلف",
    humidityLevel: "مستوى الرطوبة النسبية لحاوية النقل المبردة",
    preCoolingProtocol: "بروتوكول المعالجة بالتبريد المائي السريع الفوري",
    maxDuration: "العمر التخزيني المقدر للشحنة بأعلى معايير جودة",
    freshExchange: "معدل تبديل الهواء النقي المطلوب للبراد اللوجستي",
    packagingWeight: "الوزن الصافي للصندوق الخشبي أو الكرتوني المعتمد",
    reeferCap: "السعة اللوجستية التقديرية للبراد القياسي الكبير",
    cargoHandling: "إرشادات السلامة الخاصة لعناية ومناولة كرتون الشحن",
    // New Sections
    coldChainScheme: "● نظام تأمين سلسلة التبريد للسلع",
    coldChainTitle: "إدارة التبريد المباشر من البساتين إلى المستلم",
    coldChainDesc: "نحن نراقب بشكل صارم مؤشرات التهوية الجوية ومستشعرات الضغط في غرف النقل من المزارع وحتى التخليص الجمركي:",
    stage01Title: "المعالجة بالتبريد المائي الفوري",
    stage01Desc: "يتم خفض درجة ثمار الشحنة في غضون 4 ساعات لوقف عملية زوال السكريات الفطرية الطبيعية.",
    stage02Title: "فرز بالليزر الإلكتروني للمواصفات",
    stage02Desc: "فحص رقمي للأقطار واللون وتفادي الحبوب غير المتماثلة في التصنيف.",
    stage03Title: "تعديل أجواء التعبئة بالنيتروجين",
    stage03Desc: "التعبئة في صناديق مجهزة تضمن استخلاص غاز الإيثيلين للمحافظة على التوازن والقرمشة.",
    stage04Title: "النقل المبرد بأجهزة تتبع Telemetry",
    stage04Desc: "شاحنات أسطولنا تحافظ على بيانات الرطوبة المناسبة طيلة مسار الشحن الدولي.",
    stepByStepPrep: "⚙️ خطوات التحضير وتجهيز الشحنات",
    prodPackingProcess: "خط التعبئة والتصنيف الهيدروليكي",
    prodPackingDesc: "نهجنا الصارم يضمن تقديم محصول {product} بأعلى درجة طزاجة ومقاومة؛ حيث يخضع {product} لفرع الفرز الآلي وتنسيقه في علب مطابقة للمواصفات الخليجية.",
    complianceSafety: "🛡️ معايير الرقابة والشهادات الدولية",
    qualitySafetyTitle: "سلامة وجودة الشحنات ومطابقتها",
    qualitySafetyDesc: "جودة المنتجات ورضا العملاء هي الركيزة الأساسية لوحدة التصدير. يشرف خبراؤنا على تجهيز {product} للتأكد من خلوه من العفن والآفات الزراعية.",
    facilityWalkthrough: "جولة مرئية داخل مستودع الفرز والتبخير لجيلان",
    liveFootageTitle: "فيديو حي من مجمع فرز وتبريد غيلافروت",
    sortingFacility: "وحدة الفرز والتحضير",
    videoLength: "📹 مركز التعبئة بشمال جمهورية إيران - ٢:١٤ دقيقة",
    loadingVideoStream: "جاري بث لقطات حية من المستودع المحاذي للميناء...",
    closePlayback: "إغلاق مشغل الفيديو",
    faqHeader: "الأسئلة الأكثر تداولا تجارياً",
    faqTitle: "دليل ووثائق الشراء اللوجستي والتسليم الدولي",
    secureSupplies: "🌟 توريد مباشر بارخص الأسعار من بساتين الشمال",
    whyInternational: "لماذا يفضل الوكلاء التجاريون شركة GilaFruit؟",
    volSupplyTitle: "قدرة توريد مستمرة وعقود تناج ضخمة",
    volSupplyDesc: "تملك الشركة مزارع بمساحات شاسعة في أستارا وتالش مما يتيح الوفاء بالكميات التي تفوق ٢٠٠٠ طن بالموسم.",
    coldWarehousingTitle: "مستودعات تبريد لوقف التلف وغاز الإيثيلين",
    coldWarehousingDesc: "سعة تبريد هائلة بمراقبة الحسابات الذكية لثنائي أكسيد الكربون لضمان متانة أنسجة المحاصيل.",
    customsTransitTitle: "وثائق جمركية وتخليص سريع في منافذ أستارا",
    customsTransitDesc: "قسم إداري يخلص المعاملات وإصدار شهادة الصحة النباتية وتسجيل أوراسيا بشكل فوري بدون سماسرة.",
    packingPricingTitle: "توزيع تنافسي للموزعين بدون وسطاء",
    packingPricingDesc: "إدارتنا لفرص الحصاد اليومية، النقل، الكرتنة وحتى أسطول النقل يجعلنا المصدر الأقل سعراً لفرص الجملة.",
    strategicAdvantages: "🚀 المزايا اللوجستية للمجموعة",
    advantagesOfCompany: "مزايا الشراء المباشر من مزارعنا",
    advantagesIntro: "تضمن لك GilaFruit باقة من المزايا الحصرية التي تدعم تمويل شحنات {product} بالجملة:",
    adv1Title: "كميات تصديرية وفيرة دائمًا",
    adv1Desc: "بفضل التزاماتنا طويلة الأجل مع شبكات المزارعين نلبي شحنات {product} الطازج بانتظام طوال شهور العام.",
    adv2Title: "تنوع كلي للأقطار والأصناف",
    adv2Desc: "نقوم بتصنيف {product} حسب الأبعاد ومستويات بريكس الملائمة لاحتياجات منافذ السوبرماركت في دبي وباقي الدول.",
    adv3Title: "تكييف العلب وحجم الكرتون",
    adv3Desc: "شحن وفق أشكال التعبئة المفضلة للعميل وتزويد الحاويات بعلامات تتبع إلكترونية.",
    adv4Title: "توصيل آمن ونقل مبرد فائق السرعة",
    adv4Desc: "رحلات لوجستية منتظمة تضمن توصيل البضائع بأسرع وقت لضمان عدم تعرض الأنسجة للجفاف.",
    adv5Title: "الأسعار الأرخص على الإطلاق للعملاء",
    adv5Desc: "حذف تام لأرباح مكاتب الوساطة ومزودي السمسرة وتوفير السعر الحقيقي لـ {product} الإيراني المتميز.",
    exportDestinations: "🌍 وجهات النقل الخارجي النشطة",
    targetMarkets: "الأسواق المستهدفة والشحن",
    targetMarketsDesc: "مواصفات {product} لدينا حازت على ثقة كبرى مراكز التسوق في روسيا، بيلاروسيا، أذربيجان، تركيا وموانئ الخليج العربي.",
    mktRussia: "روسيا الاتحادي",
    mktBelarus: "بيلاروسيا",
    mktAzerbaijan: "أذربيجان",
    mktGeorgia: "جورجيا",
    mktArmenia: "أرمينيا",
    mktTurkey: "تركيا ورومانيا",
    mktPersianGulf: "دول الخليج العربي",
    connectWithSales: "📞 الاتصال المباشر بقسم المبيعات الدولية",
    contactUsTitle: "اتصل بنا",
    contactUsDesc: "تواصل مع مستشاري التصدير لشركة غيلافروت للحصول على قوائم الأسعار لـ {product} وحجز تريلات الكانتينرات المبردة.",
    whatsappHelp: "دعم فوري ومراسلة واتساب",
    industrialExcellence: "📷 صور حية لتوثيق الجودة ومستويات العمل",
    galleryDetailsTitle: "وحدة التجهيز والتدقيق الصحي والتبريد المائي",
    galleryDetailsDesc: "ألق نظرة على مستودعات ومحطات تجهيز بضائع التصدير للجمهوريات الشمالية:",
    step01Title: "صناديق بلاستيكية معقمة ومقاومة للكسر",
    step01Desc: "تعبئة وفق توصيات الجمارك الاوراسية والمنافذ الدولية.",
    step02Title: "الفرز اليدوي وتطهير الحبوب",
    step02Desc: "تفتيش يدوي دقيق لثمرات المحاصيل لاستبعاد أي ثمار معيبة.",
    step03Title: "تصنيف الجودة والوزن كلاس A",
    step03Desc: "فرز وفق معايير الحجم المتناسق تماماً لتلبية متطلبات كبرى الأسواق الاستهلاكية.",
    step04Title: "الحزم والصف العمودي لمرونة الهواء",
    step04Desc: "تثبيت الصناديق في قواعد الخشب بأسلوب هندسي يسمح بنفاذ التيارات الهوائية للبراد.",
    step05Title: "خط الدفع الأوتوماتيكي والمراقبة الفنية",
    step05Desc: "فرز بالاشعة والمكائن لمراقبة سلامة القشرة الخارجية من التلف والخدوش.",
    step06Title: "التبخير والتبريد والوقاية من الفطريات",
    step06Desc: "سحب الرطوبة ومسببات العفن لحفظ متانة الشحنة للرحلات الطويلة الشاقة عبر الحدود.",
    clickToPreview: "معاينة الصورة بالحجم الكامل",
    reviewBoard: "مجلس آراء الوكلاء والملاحة البحرية الدولية",
    reviewTitle: "شهادات وافادات كبار المستوردين والمخلصين",
    reviewDesc: "اقرأ تقييمات المكاتب والشركات التي قامت باستيراد منتجاتنا وخلّصت مستندات الشحن بموانئ دبي وموسكو.",
    verifiedAgent: "وكيل تجاري معتمد",
    registeredDispatch: "تاريخ تسجيل مانيفست الشحن والتخليص",
    helpful: "هل كانت الافادة مفيدة؟ ",
    secureTimeline: "نموذج توثيق واشهار جودة الشحنات للوكلاء",
    submitTrade: "إرسال شهادة استيراد وتقييم جودة",
    submitTradeDesc: "املأ التقرير الخاص بسلامة الكانتينرات، التخليص بمنافذ العبور وسرعة استلام البستنة. الفيلدات المميزة بنجمة مطلوبة.",
    productEvaluation: "رأيك الفني بجودة المنتج وصنف الشحنة *",
    outOfStars: "نجوم من أصل ٥ درجات للفرز",
    displayName: "الاسم الكامل للوكيل / الشركة *",
    tradeEmail: "البريد الإلكتروني للقسم التجاري للشركة *",
    wholesaleStatement: "شهادتك وتوثقيك لوصول الشحنة *",
    statementPlaceholder: "صف بدقة أوزان وجودة الشحنة وطرق التنسيق والتخليص الجمركي بمرتكزات الموانئ...",
    notRobot: "لست برنامج روبوت",
    postStatement: "إرسال وتوثيق الافادة رسمياً",
    cargoSuccess: "تم تسجيل افادة الجودة للشحنة بنجاح لعرضها تالياً بالمنصة."
  },
  tr: {
    backToDirectory: "Kataloğa Geri Dön",
    varietyStandard: "Çeşit Standardı",
    calibratedWeight: "Kalibre Edilmiş Ağırlık",
    flavorProfile: "Lezzet Profili",
    naturalColorTone: "Doğal Renk Tonu",
    coreDimensions: "Çekirdek Boyutları",
    brixSugarIndex: "Brix Şeker Endeksi",
    bulkPackingStyle: "Dökme Paketleme Tarzı",
    hsCustomsCode: "HS Gümrük Kodu",
    geographicalOrigin: "Coğrafi Köken",
    exportSeason: "İhracat Sezonu",
    primaryBatch: "★ BİRİNCİL HASAT",
    reeferStability: "⚡ YÜKSEK FRİGO STABİLİTESİ",
    sourcedInGilan: "🍀 %100 GİLAN KAYNAKLI",
    datasheetTitle: "Mahsul Özellikleri Veri Sayfası",
    exportGrade: "İHRACAT SINIFI A+",
    customRegulations: "İhracat gümrük düzenlemeleri geçiş izinlerini belirler.",
    consultDesk: "İhracat Masamıza Danışın 🟢",
    fastResponse: "5 dakikadan kısa sürede hızlı yanıt",
    yourName: "Adınız *",
    whatsappMobile: "WhatsApp Numaranız *",
    yourEmail: "E-postanız *",
    representativesContactNotice: "⚠️ Türkçe, Rusça ve Farsça temsilcilerimiz sizinle doğrudan iletişime geçecektir.",
    calculateFob: "Hesapla ve FOB Gönder",
    processing: "İşleniyor...",
    estimatesLoaded: "Tahminler Yüklendi!",
    estimatesLoadedDesc: "Kargo metrik tonajınızı işledik ve tam nakliye faktörlerini derledik. Doğrudan satış görüşmesini buradan başlatabilirsiniz:",
    openSalesDesk: "Satış Masasını Aç",
    productNotFound: "Ürün Bulunamadı",
    productNotFoundDesc: "Aradığınız ürün mevcut katalogda bulunamadı.",
    returnToDirectory: "Kataloğa geri dön",
    tonnageCalculator: "İNTERAKTİF LOJİSTİK KAPASİTE TAHMİNİ",
    metricTonnage: "İstenen Metrik Tonaj:",
    calcEstimates: "Brüt ağırlıklara göre otomatik olarak hesaplanan lojistik tahminleri.",
    tempParam: "Çekirdek Sıcaklık Parametreleri",
    humidityLevel: "Ortam Bağıl Nem Seviyesi",
    preCoolingProtocol: "Ön Soğutma Hidro-Uygulama Protokolü",
    maxDuration: "Tahmini Raf Ömrü Limiti",
    freshExchange: "Gerekli Frigo Tır Hava Değişimi",
    packagingWeight: "Standart Kutu Başına Ağırlık",
    reeferCap: "Standart Frigo Tır Kapasite İndeksi",
    cargoHandling: "Kargo Taşıma Özel Talimatları",
    // New Sections
    coldChainScheme: "● SOĞUK ZİNCİR KORUMA PROGRAMI",
    coldChainTitle: "Tarladan Palete Titiz Soğutmalı Süreç",
    coldChainDesc: "Hazar bölgesindeki bahçelerden son gümrük kontrollerine kadar atmosferik değerleri izliyoruz. Gümrük sevkiyatlarımız kontrol altındadır:",
    stage01Title: "Ön Soğutma Hidro-Uygulaması",
    stage01Desc: "Şeker bozulmasını önlemek için su soğutma şebekesi ile çekirdek sıcaklığı 4 saatte düşürülür.",
    stage02Title: "Optik Kalibrasyon",
    stage02Desc: "Çift lensli dijital kameralar dış yüzey bütünlüğünü ve renk kusurlarını saniye saniye izler.",
    stage03Title: "Azotlu Ambalajlama",
    stage03Desc: "Havanın nem ve etilen dengesi ayarlanarak kutu içi mutlak tazelik kilitlenir.",
    stage04Title: "Mühürlü Frigo Taşımacılık",
    stage04Desc: "Tırlarımız Gilan depolarından varış noktasına kadar kesintisiz telemetrik sıcaklık sağlar.",
    stepByStepPrep: "⚙️ ADIM ADIM İŞLEME VE HAZIRLIK",
    prodPackingProcess: "Üretim ve Paketleme Süreci",
    prodPackingDesc: "Müşterilerimizin taleplerine uygun olarak temizlenen, ayıklanan taze {product} ürünlerini hijyenik sepetlerde paketliyoruz.",
    complianceSafety: "🛡️ UYGUNLUK VE GÜVENLİK DAMGASI",
    qualitySafetyTitle: "Kalite ve Ürün Güvencesi",
    qualitySafetyDesc: "GILAFRUIT olarak kaliteyi önemsiyoruz. Uzmanlarımız {product} üretimi, paketleme ve sertifikalandırma aşamalarını titizlikle yönetir.",
    facilityWalkthrough: "TESİS SANAL GEZİSİ",
    liveFootageTitle: "Gilan Paketleme Evi Canlı Görüntüler",
    sortingFacility: "Sınıflandırma Tesisi",
    videoLength: "📹 Ayıklama Merkezi Videosu - 2:14 dk",
    loadingVideoStream: "Astara deposundan canlı video yükleniyor...",
    closePlayback: "Oynatıcıyı Kapat",
    faqHeader: "SIKÇA SORULAN SORULAR",
    faqTitle: "Toptan Satın Alım Talimatları",
    secureSupplies: "🌟 DOĞRUDAN BAHÇEDEN SEVKİYAT GÜVENCESİ",
    whyInternational: "Yabancı Alıcılar Neden GilaFruit'u Seçiyor?",
    volSupplyTitle: "Düzenli ve Büyük Hacimli Tedarik",
    volSupplyDesc: "Astara ve Talesh'teki kivi bahçelerimiz sayesinde sezon boyunca 2000 tona yakın hacmi başarıyla karşılıyoruz.",
    coldWarehousingTitle: "Etilen Filtreli Gelişmiş Soğuk Depolar",
    coldWarehousingDesc: "Depolarımızda etilen birikimi izlenir, bağıl nem ayarlanarak hücre bozulması önlenir.",
    customsTransitTitle: "Ön Gümrükleme Hizmetleri",
    customsTransitDesc: "Yenilikçi gümrük birimimiz bitki sağlık sertifikalarını, EAC beyannamelerini Astara sınırında hızla çözer.",
    packingPricingTitle: "Aracısız Paketleme Evi Fiyatları",
    packingPricingDesc: "Hasat, srtlama, kartonlama ve lojistik filoyu yöneterek tüm aracı komisyonlarını devredışı bırakıyoruz.",
    strategicAdvantages: "🚀 Stratejik Avantajlar",
    advantagesOfCompany: "Şirketimizden Almanın Sağladığı Faydalar",
    advantagesIntro: "İran tarımı küreselleşirken Gilafruit, yüksek hacimli toptan {product} siparişlerinizde en iyi fırsatı sunar:",
    adv1Title: "Büyük miktarda tedarik",
    adv1Desc: "Çiftçilerle uzun süreli anlaşmalarımız, taze {product} tedariğinin yıl boyu kesintisiz sunulmasını sağlar.",
    adv2Title: "Zengin çeşitlilik ve kalibre",
    adv2Desc: "Avrupa ve Körfez pazarına uygun, aradığınız kalibre ve lezzette {product} çeşitlerini sınıflara ayırıyoruz.",
    adv3Title: "Markalı özel paketleme",
    adv3Desc: "Müşterinin karton ve sandık taleplerine göre paketlerin mukavemetini uzun yollara göre ayarlıyoruz.",
    adv4Title: "Garantili frigo lojistik",
    adv4Desc: "Kalite kaybını önlemek için en iyi sıcaklık kontrollü tırlarımızla hızlı sevkiyatlar yapıyoruz.",
    adv5Title: "En iyi doğrudan fiyatlar",
    adv5Desc: "Aracıları ortadan kaldırarak İran {product} ürünlerinde en avantajlı toptan fiyat seviyesini sunuyoruz.",
    exportDestinations: "🌍 İhracat Yapılan Bölgeler",
    targetMarkets: "Hedef Pazarlar",
    targetMarketsDesc: "{product} ürünlerimiz yüksek aromasıyla Rusya, Belarus, Azerbaycan, Gürcistan, Türkiye ve Körfez ülkelerinde yoğun ilgi görür.",
    mktRussia: "Rusya",
    mktBelarus: "Belarus",
    mktAzerbaijan: "Azerbaycan",
    mktGeorgia: "Gürcistan",
    mktArmenia: "Ermenistan",
    mktTurkey: "Türkiye",
    mktPersianGulf: "Arap Körfezi Ülkeleri",
    connectWithSales: "📞 SATIŞ DESTEK HATTI",
    contactUsTitle: "Bize Ulaşın",
    contactUsDesc: "Toptan {product} fiyatları ve tır organizasyon detayları için WhatsApp veya e-posta yoluyla bize doğrudan ulaşın.",
    whatsappHelp: "WhatsApp Destek Hattı",
    industrialExcellence: "📷 ÜRETİM ADIMLARINDAN KARELER",
    galleryDetailsTitle: "Gilan Paketleme, Sınıflandırma ve Soğuk Hava Deposu",
    galleryDetailsDesc: "Gilan bölgesindeki uluslararası nakliye temizleme tesisimizden kareler:",
    step01Title: "Hijyenik Plastik Transfer Sepetleri",
    step01Desc: "Sınır kapısı kurallarına uygun tasarlanmış yüksek taşıma dirençli kasalar.",
    step02Title: "El İle Hassas Seçim Aşaması",
    step02Desc: "Çürük veya hasarlı ürünlerin uzman personelimizce hattan ayıklanması.",
    step03Title: "Premium Kalibre Sınıflandırması",
    step03Desc: "Piyasa isteklerine göre eşit ebatlarda paketlenmiş yüksek gümrük standardı.",
    step04Title: "Tırçi Hava Kanallı İstifleme",
    step04Desc: "Kutuların tır içerisinde rüzgar akımına izin verecek şekilde paletlenmesi.",
    step05Title: "Mekanik Sınıflandırma Üniteleri",
    step05Desc: "Taze ürünlerin kabuk bütünlüğünün ve sertliğinin optik sensörlerle ölçümü.",
    step06Title: "Kuruluş ve Nem Alma İşlemi",
    step06Desc: "Avrasya hattındaki uzun yollar sırasında küf oluşumunu önleyici nem emilimi.",
    clickToPreview: "GÖRSELİ BÜYÜT",
    reviewBoard: "İTHALATÇI VE BAYİ FORUMU",
    reviewTitle: "Tüccar ve Gümrük Acentelerinin Görüşleri",
    reviewDesc: "GilaFruit'ten ürün ithal eden ve evrak işlemlerini tamamlayan yabancı alıcıların gerçek beyanları.",
    verifiedAgent: "Doğrulanmış Tüccar",
    registeredDispatch: "Gümrük Çıkış ve Tır Sevk Tarihi",
    helpful: "Yorum faydalı mı? ",
    secureTimeline: "TİCARİ DEĞERLENDİRME VE GÜVENCE BİLDİRİMİ",
    submitTrade: "Ticari Görüş ve Geri Bildirim Formu",
    submitTradeDesc: "Sevkiyat kalitesi, evrak hazırlığı ve gümrük hızı hakkındaki görüşlerinizi ekleyin. Yıldızlı alanlar zorunludur.",
    productEvaluation: "Ürün Kalite Değerlendirmesi *",
    outOfStars: "yıldız / 5 Kalite Seviyesi",
    displayName: "Adınız Soyadınız / Ticari Ünvanınız *",
    tradeEmail: "Şirket Kurumsal E-posta Adresiniz *",
    wholesaleStatement: "Sevkiyat Teslimat Değerlendirmeniz *",
    statementPlaceholder: "Malzemenin kalibresi, gümrük geçiş hızı ve şirket destek seviyesini belirtin...",
    notRobot: "Ben robot değilim",
    postStatement: "Değerlendirmeyi Yayınla",
    cargoSuccess: "Geri bildiriminiz alındı! Spam taramasından sonra yayına alınacaktır."
  },
  az: {
    backToDirectory: "Kataloqa Geri Dön",
    varietyStandard: "Sort Standartı",
    calibratedWeight: "Kalibrasiya olunmuş Çəki",
    flavorProfile: "Dad və Ətir Profili",
    naturalColorTone: "Təbii Rəng Tonu",
    coreDimensions: "Əsas Ölçülər",
    brixSugarIndex: "Brix Şəkər İndeksi",
    bulkPackingStyle: "Topdan Qablaşdırma Üslubu",
    hsCustomsCode: "HS Gömrük Kodu",
    geographicalOrigin: "Coğrafi Mənşə",
    exportSeason: "İxrac Mövsümü",
    primaryBatch: "★ BİRİNCİ DƏRƏCƏLİ PARTİYA",
    reeferStability: "⚡ YÜKSƏK REF STABİLLİYİ",
    sourcedInGilan: "🍀 100% GİLAN MƏHSULU",
    datasheetTitle: "Məhsul Xüsusiyyətləri Dataşiti",
    exportGrade: "İXRAC GRADE A+",
    customRegulations: "İxrac gömrük qaydaları tranzit rəsmiləşdirilməsini müəyyən edir.",
    consultDesk: "İxrac Şöbəmizlə Məsləhətləşin 🟢",
    fastResponse: "5 dəqiqədən az müddətdə sürətli cavab",
    yourName: "Adınız *",
    whatsappMobile: "WhatsApp Nömrəniz *",
    yourEmail: "E-poçtunuz *",
    representativesContactNotice: "⚠️ Rus, Azərbaycan və fars dilli nümayəndələrimiz sizinlə birbaşa əlaqə saxlayacaqlar.",
    calculateFob: "Hesabla və FOB Sorğusu Göndər",
    processing: "Emal olunur...",
    estimatesLoaded: "Hesablamalar Hazırdır!",
    estimatesLoadedDesc: "Kargo metrik tonajınızı emal etdik qablaşdırma amillərini topladıq. Buradan birbaşa satış söhbətinə başlaya bilərsiniz:",
    openSalesDesk: "Satış Şöbəsini Aç",
    productNotFound: "Məhsul Tapılmadı",
    productNotFoundDesc: "İstədiyiniz məhsul beynəlxalq katalogda mövcud deyil.",
    returnToDirectory: "Dizinə geri dön",
    tonnageCalculator: "İNTERAKTİV YÜK TUTUMU QİYMƏTLƏNDİRİLMƏSİ",
    metricTonnage: "Arzu olunan Metrik Tonaj:",
    calcEstimates: "Ümumi çəkiyə əsasən avtomatik hesablanan real vaxt logistika qiymətləndirmələri.",
    tempParam: "Məhsulun Daxili Temperaturu",
    humidityLevel: "Nisbi Rütubət Səviyyəsi",
    preCoolingProtocol: "İlkin Soyutma Hidro-Emal Protokolu",
    maxDuration: "Təxmini Raf Ömrü Limiti",
    freshExchange: "Tələb olunan Təzə Hava Mübadiləsi",
    packagingWeight: "Standart Qutu Başına Çəki",
    reeferCap: "Standart Refer Konteyner Tutumu",
    cargoHandling: "Yükün Daşınması üzrə Xüsusi Təlimatlar",
    // New Sections
    coldChainScheme: "● SOĞUQ ZƏNCİR PROQRAMI",
    coldChainTitle: "Tarladan Paletə Soyuduculu Daşınma",
    coldChainDesc: "Yüklərin sıradan çıxmaması üçün bütün mərhələlərdə temperaturu izləyirik. Astara terminalından daşınmalar nəzarətdədir:",
    stage01Title: "İlkin Hidro-Soyutma",
    stage01Desc: "Şəkərin parçalanmasını önləmək üçün daxili temp 4 saatda endirilir.",
    stage02Title: "Optik Kalibrasiya",
    stage02Desc: "İki lensli rəqəmsal kameralar yeşiklərin rəng və keyfiyyətini seçir.",
    stage03Title: "Azot Ambalajı",
    stage03Desc: "Etilen uzaqlaşdırıcı vasitələrlə məhsulun təravəti qorunur.",
    stage04Title: "Möhürlənmiş Ref Tırlar",
    stage04Desc: "Gilan anbarlarından təhvil nöqtəsinə qədər temperatur məlumatları qeyd olunur.",
    stepByStepPrep: "⚙️ HAZIRLIQ VƏ SEÇİLMƏ MƏRHƏLƏLƏRİ",
    prodPackingProcess: "İstehsal və Qablaşdırma Prosesi",
    prodPackingDesc: "Təmizlənmiş, seçilmiş təzə {product} məhsullarını beynəlxalq standartlara uyğun qablarda qablaşdırırıq.",
    complianceSafety: "🛡️ STANDARTLARA UYĞUNLUQ",
    qualitySafetyTitle: "Məhsul Keyfiyyəti Zəmanəti",
    qualitySafetyDesc: "Mütəxəssislərimiz {product} yığılması və sənədləşməsini beynəlxalq phytosanitar tələblərlə tənzimləyir.",
    facilityWalkthrough: "FABRİKDƏN GÖRÜNTÜLƏR",
    liveFootageTitle: "Gilan Sürətli Səbətləmə Evindən Video",
    sortingFacility: "Seçmə Sahəsi",
    videoLength: "📹 Ayıklama Mərkəzi - 2:14 dəq",
    loadingVideoStream: "Astara anbarındakı kameradan canlı yayım...",
    closePlayback: "Pleyeri Bağla",
    faqHeader: "TEZ-TEZ VERİLƏN SUALLAR",
    faqTitle: "Topdansatış Alış Təlimatları",
    secureSupplies: "🌟 BİRBAŞA BAĞLARDAN ALVİR SƏRFƏSİ",
    whyInternational: "Xarici Alıcılar Niyə GilaFruit-u Seçirlər?",
    volSupplyTitle: "Davamlı və Böyük Həcmli Tədarük",
    volSupplyDesc: "Astara və Taleshdəki kivi bağlarımız vasitəsilə 2000 tona qədər sifarişləri rəsmiləşdirə bilirik.",
    coldWarehousingTitle: "Etilen Filtirli Soyuq Depolar",
    coldWarehousingDesc: "Depolarda rütubət nəzarət altında saxlanılaraq kiflənmənin qarşısı alınır.",
    customsTransitTitle: "Gömrük Sənədlərinin Tezləşdirilməsi",
    customsTransitDesc: "Peşəkar heyətimiz phytosanitar sənədləri və EAC deklarasiyasını Astara gömrüyündə həll edir.",
    packingPricingTitle: "Vasitəçisiz Satış Qiyməti",
    packingPricingDesc: "Hasat, çeşidləmə, qablaşdırma və daşınmanı idarə edərək vasitəçiləri rədd edirik.",
    strategicAdvantages: "🚀 Strateji Üstünlüklər",
    advantagesOfCompany: "Şirkətimizdən Alışın Üstünlükləri",
    advantagesIntro: "GilaFruit irihəcmli {product} sifarişləriniz üzrə ən yaxşı rəqabətli qiymətləri təmin edir:",
    adv1Title: "Çox böyük həcmdə təchizat",
    adv1Desc: "Fermerlərlə bağlanan birbaşa müqavilələr ilboyu keyfiyyətli {product} tədarükünü təmin edir.",
    adv2Title: "Sortların zənginliyi",
    adv2Desc: "İxrac bazarlarına uyğun hər növ {product} çeşidləməsini kalibrlərlə həyata keçiririk.",
    adv3Title: "İstəyə uyğun yeşik və qutu",
    adv3Desc: "Alıcının istəyinə əsasən karton və yeşik dizaynları hazırlanır.",
    adv4Title: "Sürətli soyuduculu daşınma",
    adv4Desc: "Yükün təravətini itirməməsi üçün logistika işləri sürətli rejimdə qurulub.",
    adv5Title: "Sərfəli və birbaşa qiymətlər",
    adv5Desc: "Vasitəçilərin olmaması İrandan birbaşa {product} üçün ən aşağı qiymətə zəmanət verir.",
    exportDestinations: "🌍 İxracat Coğrafiyası",
    targetMarkets: "Hədəf Bazarları",
    targetMarketsDesc: "{product} məhsulumuz Rusiya, Belarus, Türkiyə, Azərbaycan və Körfəz ölkələrində xüsusi maraq doğurur.",
    mktRussia: "Rusiya",
    mktBelarus: "Belarus",
    mktAzerbaijan: "Azərbaycan",
    mktGeorgia: "Gürcüstan",
    mktArmenia: "Ermənistan",
    mktTurkey: "Türkiyə",
    mktPersianGulf: "Körfəz Ölkələri",
    connectWithSales: "📞 SATIŞ DEPARTAMENTİ",
    contactUsTitle: "Bizimlə Əlaqə",
    contactUsDesc: "Topdansatış {product} qiymətləri və tırların sifarişi üçün WhatsApp və ya poçt vasitəsilə bizə dərhal yazın.",
    whatsappHelp: "WhatsApp Dəstəyi",
    industrialExcellence: "📷 RETROPERSPEKTİV İSTEHSAL RESİMLƏRİ",
    galleryDetailsTitle: "Gilan Seçmə və Logistika Terminalı",
    galleryDetailsDesc: "Gilan ərazisindəki ixracat hazırlıq anbarlarımızdan kadrlar:",
    step01Title: "Gigiyenik Plastik Səbətlər",
    step01Desc: "İxracat qaydalarına uyğun yüksək dözümlü səbətlər.",
    step02Title: "Məhsulun Əllə Seçilməsi",
    step02Desc: "Təcrübəli heyət yararsız məhsulları xəttdən ayırır.",
    step03Title: "Premilaum Kalibrasiya",
    step03Desc: "Bərabər ölçülərdə çeşidlənmə ilə premium gümrük keyfiyyəti.",
    step04Title: "Tırçı Hava Kanallı Yığım",
    step04Desc: "Kutuların tır daxilində hava sirkulyasiyasına uyğun yığılması.",
    step05Title: "Mexaniki Çeşidləmə Xəttləri",
    step05Desc: "Məhsulun səthinin optik sensorlarla nəzarəti.",
    step06Title: "Qurutma və Nəmliyin Aradan Qaldırılması",
    step06Desc: "Rusiya istiqamətindəki dözümlülük üçün nəm əmilməsi.",
    clickToPreview: "ŞƏKLİ BÖYÜT",
    reviewBoard: "TÜCCAR VƏ ALICI FORUMU",
    reviewTitle: "İdxalçıların və Brokerlərin Rəyləri",
    reviewDesc: "GilaFruit daxilində ticarəti tamamlamış müştərilərin rəsmi fikirləri.",
    verifiedAgent: "Doğrulanmış Tüccar",
    registeredDispatch: "Gömrük Çıxış və Sevk Tarixi",
    helpful: "Faydalı? ",
    secureTimeline: "TİCARİ KEYFİYYƏT BƏYANATI",
    submitTrade: "Rəy və Təklif Formu",
    submitTradeDesc: "Sevkiyat, gümrük xidməti haqqında rəyinizi yazın. Ulduzlu xanalar vacibdir.",
    productEvaluation: "Məhsul Keyfiyyəti *",
    outOfStars: "ulduz / 5 Keyfiyyət",
    displayName: "Adınız Soyadınız / Vəzifəniz *",
    tradeEmail: "Korporativ E-poçtunuz *",
    wholesaleStatement: "Sevkiyat Qiymətləndirilməsi *",
    statementPlaceholder: "Məhsulun kalibri, sənədlərin hazırlanma sürəti barədə məlumat yazın...",
    notRobot: "Mən robot deyiləm",
    postStatement: "Rəyi Göndər",
    cargoSuccess: "Rəyiniz qəbul edildi! Spam yoxlanışından sonra saytda dərc olunacaq."
  },
  uz: {
    backToDirectory: "Katalogga Qaytish",
    varietyStandard: "Nav standarti",
    calibratedWeight: "Kalibrlangan og'irlik",
    flavorProfile: "Ta'm va hid xususiyati",
    naturalColorTone: "Tabiiy rang toni",
    coreDimensions: "Asosiy o'lchamlari",
    brixSugarIndex: "Brix shakar ko'rsatkichi",
    bulkPackingStyle: "Yirik qadoqlash uslubi",
    hsCustomsCode: "HS bojxona kodi",
    geographicalOrigin: "Geografik kelib chiqishi",
    exportSeason: "Eksport mavsumi",
    primaryBatch: "★ BIRINCHI NAVBATDAGI YUK",
    reeferStability: "⚡ YUQORI RAF BARQARORLIGI",
    sourcedInGilan: "🍀 100% GILAN MAHSULOTI",
    datasheetTitle: "Mahsulot xususiyatlari jadvali",
    exportGrade: "EKSPORT GRADI A+",
    customRegulations: "Eksport bojxona qoidalari tranzitga ta'sir qiladi.",
    consultDesk: "Eksport bo'limimizga murojaat qiling 🟢",
    fastResponse: "5 daqiqadan kamroq vaqt ichida tezkor javob",
    yourName: "Ismingiz *",
    whatsappMobile: "Telefon/WhatsApp raqamingiz *",
    yourEmail: "Elektron pochtangiz *",
    representativesContactNotice: "⚠️ Savdo xodimlarimiz siz bilan o'zbek, rus va fors tillarida bevosita bog'lanishadi.",
    calculateFob: "FOB narxini hisoblash",
    processing: "Ishlanmoqda...",
    estimatesLoaded: "Hisob-kitoblar tayyor!",
    estimatesLoadedDesc: "Yuk hajmini tahlil qilib, aniq logistika omillarini tayyorladik. To'g'ridan-to'g'ri aloqani boshlashingiz mumkin:",
    openSalesDesk: "Savdo bo'limini ochish",
    productNotFound: "Mahsulot topilmadi",
    productNotFoundDesc: "Tanlangan mahsulot xalqaro katalogda mavjud emas.",
    returnToDirectory: "Katalogga qaytish",
    tonnageCalculator: "INTERAKTIV YUK LOHIHA HISOB-KITOBI",
    metricTonnage: "Kerakli og'irlik (metr tonna):",
    calcEstimates: "Umumiy og'irlikka ko'ya avtomatik hisoblangan real vaqt logistika baholari.",
    tempParam: "Qadoqlangan mahsulot harorati",
    humidityLevel: "Tavsiya etilgan namlik darajasi",
    preCoolingProtocol: "Gidro-sovitish maxsus protokoli",
    maxDuration: "Taxminiy saqlash muddati",
    freshExchange: "Konteyner ventilyatsiyasi talabi",
    packagingWeight: "Standart quti og'irligi",
    reeferCap: "Standart sovutgichli yuk mashinasi hajmi",
    cargoHandling: "Yukni saqlashga doir maxsus ko'rsatmalar",
    // New Sections
    coldChainScheme: "● MUZLATGICH ZANJIRI DASTURI",
    coldChainTitle: "Dalaning o'zidan Sovutgichli Transport",
    coldChainDesc: "Yaroqlilikni saqlash uchun har bir bosqichda haroratni nazorat qilamiz. Astara bojxona punktidagi sifat mufassal nazoratimizda:",
    stage01Title: "Dastlabki Gidro-Sovitish",
    stage01Desc: "Shakar buzilishining oldini olish uchun ichki temp 4 soatda tushiriladi.",
    stage02Title: "Optik Kalibrlash",
    stage02Desc: "Ikki kamerali raqamli tizim meva rangi va hajmini tanlaydi.",
    stage03Title: "Azot Muhofazasi",
    stage03Desc: "Etilen yutuvchilar yordamida mahsulot tarovati mahkam saqlanadi.",
    stage04Title: "Muhrlangan Ref Yuk Tirlari",
    stage04Desc: "Gilan omborlaridan yetkazish manziliga qadar barcha harorat qayd qilinadi.",
    stepByStepPrep: "⚙️ QADOM-BA-QADOM TAYYORLASH TIZIMI",
    prodPackingProcess: "Ishlab chiqarish va qadoqlash jarayoni",
    prodPackingDesc: "Tozalangan va saralangan sarxil {product} mahsulotlarini xalqaro standart qutilarda taqdim qilamiz.",
    complianceSafety: "🛡️ XALQARO STANDART MUVOFIQLIGI",
    qualitySafetyTitle: "Mahsulot sifati kafolati",
    qualitySafetyDesc: "Mutaxassislarimiz {product} yig'ish va sertifikatlash bosqichlarini bevosita boshqaradi.",
    facilityWalkthrough: "KORXONADAGI JALB ETUVCHI HOLAT",
    liveFootageTitle: "Gilan Saralash Markazi Jonli Tasvirlar",
    sortingFacility: "Saralash Korxonasi",
    videoLength: "📹 Markaz videosi - 2:14 daq",
    loadingVideoStream: "Astara anboridan jonli video uzatilmoqda...",
    closePlayback: "Pleyerni Yopish",
    faqHeader: "KO'P YO'LLANADIGAN SAVOLLAR",
    faqTitle: "Ulgurji Xarid Bo'yicha Yo'riqnomalar",
    secureSupplies: "🌟 DO'STONA TO'G'RIDAN-TO'G'RI BOG'DAN ETKAZISH",
    whyInternational: "Import qiluvchilar nega GilaFruitni tanlashadi?",
    volSupplyTitle: "Doimiy va Katta Hajmdagi Tovar",
    volSupplyDesc: "Astara va Taleshdagi kivi bog'larimiz orqali 2000 tonnagacha sifarlarni oson rasmilashtiramiz.",
    coldWarehousingTitle: "Etilen Filtrli Zamonaviy Sovuq Depolar",
    coldWarehousingDesc: "Depolarda namlik darajasi me'yorda saqlanib, mog'orlanishni oldi olinadi.",
    customsTransitTitle: "Tezkor Bojxona Senedlarini Rassmiylashtirish",
    customsTransitDesc: "Bojxona xizmati bitki-sanitariya va EAC deklaratsiyasini chegarada zudlik bilan hal qiladi.",
    packingPricingTitle: "Vositalarsiz Eshik Narxlari",
    packingPricingDesc: "Hosilni yig'ish, saralash, qutilash va yuk mashinalarini boshqarib, vositachilarni chetda qoldiramiz.",
    strategicAdvantages: "🚀 Strategik imkoniyatlar",
    advantagesOfCompany: "Kompaniyamizdan sotib olishning afzalliklari",
    advantagesIntro: "Eksport imkoniyatlari kengayib bormoqda, GilaFruit toptan {product} bo'yicha eng past narxlarni taklif etadi:",
    adv1Title: "Katta hajmdagi ta'minot",
    adv1Desc: "Fermerlar bilan tuzilgan uzoq muddatli shartnomalar yil davomida turg'un {product} ta'minlashga zamin yaratadi.",
    adv2Title: "Turli xil navlar va kalibrlar",
    adv2Desc: "Eksport talablari asnosida har bir navni o'lchamlar bo'yicha klassifikatsiyalaymiz.",
    adv3Title: "Xohishingizga ko'ra quti va korob",
    adv3Desc: "Mijoz buyurtmasiga ko'ra maxsus korob va qutilar dizayni tayyorlanadi.",
    adv4Title: "Tezkor va xavfsiz ref yuk tashish",
    adv4Desc: "Mahsulot yangiligini saqlash maqsadida tirlarni tezkor rejimda yo'lga chiqaramiz.",
    adv5Title: "Erkin va eng past narxlar",
    adv5Desc: "Vositachilarning chetlatilishi tufayli {product} uchun eng past narx kafolatlanadi.",
    exportDestinations: "🌍 Eksport Hududlari",
    targetMarkets: "Maqsadli Bozorlar",
    targetMarketsDesc: "{product} mahsulotimiz o'zining yuqori sifati bilan Rossiya, Belarus, Turkiya, Ozarbayjon va Fors ko'rfazi davlatlarida mashhur.",
    mktRussia: "Rossiya",
    mktBelarus: "Belarus",
    mktAzerbaijan: "Ozarbayjon",
    mktGeorgia: "Gruziya",
    mktArmenia: "Armaniston",
    mktTurkey: "Turkiya",
    mktPersianGulf: "Ko'rfaz Davlatlari",
    connectWithSales: "📞 SAVDO BO'LIMI ALOQASI",
    contactUsTitle: "Biz bilan bog'lanish",
    contactUsDesc: "Ulgurji {product} narxlari va transport bo'yicha WhatsApp yoki pochtamiz orqali zudlik bilan yozing.",
    whatsappHelp: "WhatsApp Ko'magi",
    industrialExcellence: "📷 RETRO ISTEHSALAT RASMLARI",
    galleryDetailsTitle: "Gilan Saralash, Paketlash va Logistika Markazi",
    galleryDetailsDesc: "Mahsulotlarimizni uzoq yo'lga tayyorlash jarayonlaridan lavhalar:",
    step01Title: "Gigiyenik Plastik Savatlar",
    step01Desc: "Bojxona talablariga mos dizayndagi toza mustahkam sepetlar.",
    step02Title: "Qo'lda Nozik Saralash Bosqichi",
    step02Desc: "Yaroqsiz mevalarni kadrlarimiz tomonidan hattan ajratilishi.",
    step03Title: "Premium Kalibrlash Ishlari",
    step03Desc: "Teng hajmdagi o'lchamlarda saralash orqali premium gümrük standarti.",
    step04Title: "Tir Ichida Havo Yo'lakli Taxi",
    step04Desc: "Qutilarni tirlar ichida havo yurishiga mos uslubda taxlash.",
    step05Title: "Mexanik Saralash Koridori",
    step05Desc: "Mahsulotlar yuzasining optik sensorlar bilan tekshirilishi.",
    step06Title: "Qurutish va Namlikni Yo'qotish",
    step06Desc: "Uzoq masofa davomida mog'orlanishga qarshi namlikni so'rilishi.",
    clickToPreview: "RASMNI KATTALASHTIRISH",
    reviewBoard: "MUTAXASSIS VÈ XARIDORLAR FORUMI",
    reviewTitle: "Importchilar va Brokerlar Fikrlari",
    reviewDesc: "GilaFruit guruhidan mahsulot sotib olgan xalqaro hamkorlarning rasmiy fikrlari.",
    verifiedAgent: "Tasdiqlangan Hamkor",
    registeredDispatch: "Bojxonadan Chiqish va Ketish Sanasi",
    helpful: "Foydalimi? ",
    secureTimeline: "TIJORIY SIFAT BAYONNOMASI",
    submitTrade: "Savol va Takliflar Formasi",
    submitTradeDesc: "Yetkazib berish xizmati haqidagi fikrlaringizni yozib qoldiring. Belgilangan maydonlar shart.",
    productEvaluation: "Mahsulot sifati *",
    outOfStars: "yulduz / 5 daraja",
    displayName: "Ismingiz / Lavozimingiz *",
    tradeEmail: "Korporativ pochtangiz *",
    wholesaleStatement: "Yetkazib berish bahosi *",
    statementPlaceholder: "Mahsulot o'lchami, senedlar tayyorlash tezligi borasida ma'lumot qoldiring...",
    notRobot: "Men robot emasman",
    postStatement: "Fikrni Yuborish",
    cargoSuccess: "Fikringiz qabul qilindi! Spam nazoratidan keyin nashr etiladi."
  },
  uk: {
    backToDirectory: "Назад до каталогу",
    varietyStandard: "Сортовий стандарт",
    calibratedWeight: "Калібрована вага",
    flavorProfile: "Смаковий профіль",
    naturalColorTone: "Природний відтінок кольору",
    coreDimensions: "Габарити калібру",
    brixSugarIndex: "Показник цукру (Брікс)",
    bulkPackingStyle: "Оптовий тип пакування",
    hsCustomsCode: "Код УКТ ЗЕД",
    geographicalOrigin: "Географічне походження",
    exportSeason: "Сезон експорту",
    primaryBatch: "★ ПЕРВИННА ПАРТІЯ ВАНТАЖУ",
    reeferStability: "⚡ ВИСОКА СТАБІЛЬНІСТЬ У РЕФРИЖЕРАТОРІ",
    sourcedInGilan: "🍀 100% ВИРОЩЕНО В ГІЛАНІ",
    datasheetTitle: "Специфікація експортного вантажу",
    exportGrade: "ЕКСПОРТНИЙ СОРТ А+",
    customRegulations: "Митні правила транзиту регулюють транзитні процедури.",
    consultDesk: "Зв'язатися з експортним відділом 🟢",
    fastResponse: "Швидка відповідь менш ніж за 5 хвилин",
    yourName: "Ваше ім'я *",
    whatsappMobile: "Ваш WhatsApp мобільний *",
    yourEmail: "Ваш Email *",
    representativesContactNotice: "⚠️ Наші представники зв'яжуться з вами російською, англійською чи перською мовою.",
    calculateFob: "Розрахувати та надіслати FOB",
    processing: "Обробка...",
    estimatesLoaded: "Розрахунки готові!",
    estimatesLoadedDesc: "Ми проаналізували параметри вашого вантажу та зібрали точні чинники транспортування. Ви можете почати діалог:",
    openSalesDesk: "Відкрити чат продажів",
    productNotFound: "Продукт не знайдено",
    productNotFoundDesc: "Обраний товар відсутній у чинній номенклатурі.",
    returnToDirectory: "Повернутися",
    tonnageCalculator: "ІНТЕРАКТИВНЕ ОЦІНЮВАННЯ ЛОГІСТИЧНИХ ФАКТОРІВ",
    metricTonnage: "Бажаний тоннаж (у метричних тоннах):",
    calcEstimates: "Автоматичний розрахунок логістичних факторів на основі брутто-ваги.",
    tempParam: "Температурний режим м'якоті продукту",
    humidityLevel: "Рівень відносної вологості камери",
    preCoolingProtocol: "Протокол попереднього охолодження водою",
    maxDuration: "Очікуваний термін зберігання вантажу",
    freshExchange: "Необхідний приплив свіжого повітря",
    packagingWeight: "Вага стандартної коробки",
    reeferCap: "Місткість стандартного рефрижератора",
    cargoHandling: "Спеціальні інструкції з вантажоперевезення",
    // New Sections
    coldChainScheme: "● ХОЛОДОВИЙ ТРАНЗИТНИЙ КЛАС",
    coldChainTitle: "Охолодження від поля до палет",
    coldChainDesc: "Контролюємо вологість від каспійських плантацій до кордону. Відправлення GilaFruit сертифікуються:",
    stage01Title: "Гідро-охолодження",
    stage01Desc: "Температура м'якоті знижується протягом 4 годин для перешкоджання руйнації цукру.",
    stage02Title: "Оптичне Сортування",
    stage02Desc: "Калібратори з двома лінзами оцінюють якість плодів та відсутність зовнішніх дефектів.",
    stage03Title: "Упаковка з азотом",
    stage03Desc: "Вентильований картон з поглиначами етилену дозволяє зберегти хрусткість вантажу.",
    stage04Title: "Рефрижератори з пломбами",
    stage04Desc: "Нові тягачі фіксують температуру та вологість протягом усього маршруту транзиту.",
    stepByStepPrep: "⚙️ ПОКРОКОВЕ СОРТУВАННЯ",
    prodPackingProcess: "Виробництво та пакувальні процеси",
    prodPackingDesc: "Ретельний відбір {product} гарантує відмінну якість. Після збору врожаю {product} очищують та логістично укладають в ящики.",
    complianceSafety: "🛡️ СЕРТИФІКАТИ ТА СТАНДАРТИ",
    qualitySafetyTitle: "Гарантія якості та митної відповідності",
    qualitySafetyDesc: "Спеціалісти GILAFRUIT стежать за сортуванням {product}, що дозволяє отримати фітосанітарну згоду в країнах імпорту.",
    facilityWalkthrough: "ПРЕЗЕНТАЦІЯ СКЛАДІВ",
    liveFootageTitle: "Відео сортувальних цехів Гілана",
    sortingFacility: "Сортувальний Склад",
    videoLength: "📹 Відео - 2:14 хв",
    loadingVideoStream: "Завантажується відео з прикордонного терміналу Астари...",
    closePlayback: "Закрити відео",
    faqHeader: "ЧАСТО ЗАДАВАНІ ПИТАННЯ",
    faqTitle: "Інструкції імпортеру для закупівель",
    secureSupplies: "🌟 ОПТОВІ СТАБІЛЬНІ ПОСТАВКИ ДЛЯ ДИСТРИБ'ЮТОРІВ",
    whyInternational: "Чому європейські компанії обирають GilaFruit",
    volSupplyTitle: "Регулярні значні обсяги вантажів",
    volSupplyDesc: "Оренда та володіння розлогими садами ківі в Астарі дозволяють виконати обсяги до 2000 тонн за сезон.",
    coldWarehousingTitle: "Технологічні склади з фільтрами етилену",
    coldWarehousingDesc: "Знижуємо рівень газів та регулюємо вологість, щоб плоди не дряпалися та не пріли під час перевезень.",
    customsTransitTitle: "Декларування товарів без затримок",
    customsTransitDesc: "Експортне бюро реєструє ЕАС та фітосанітарні папери безпосередньо в порту Астари.",
    packingPricingTitle: "Економічна ціна складів Гілану",
    packingPricingDesc: "Ми координуємо збір, пакування та логістику товарів, тому наші ціни позбавлені націнок дилерів.",
    strategicAdvantages: "🚀 Пріоритетні Переваги",
    advantagesOfCompany: "Чому вигідно замовляти у нашої компанії",
    advantagesIntro: "Gilafruit гарантує першокласні умови для закупівлі великого опту {product}:",
    adv1Title: "Великі експортні обсяги",
    adv1Desc: "Угоди з агрономами та фермерами підтримують безперебійний потік {product} відмінної форми.",
    adv2Title: "Сортова класифікація",
    adv2Desc: "Пропонуємо калібрований {product} з різним рівнем цукру для ринків дистрибуції.",
    adv3Title: "Фірмова коробка під замовлення",
    adv3Desc: "Виготовлення картону та ящиків за побажаннями клієнта для далеких відстаней.",
    adv4Title: "Перевезення з температурним звітом",
    adv4Desc: "Рефрижераторні вантажівки відправляються із записом показників для повної свіжості.",
    adv5Title: "Ціна прямого виробника в Ірані",
    adv5Desc: "Усунення перекупників надає вам найоптимальнішу цінову пропозицію на свіжий {product}.",
    exportDestinations: "🌍 Напрямки Митного Транзиту",
    targetMarkets: "Базові ринки збуту",
    targetMarketsDesc: "{product} користується попитом у торгових мережах України, Польщі, Румунії, Туреччини, Грузії та РФ.",
    mktRussia: "РФ",
    mktBelarus: "Білорусь",
    mktAzerbaijan: "Азербайджан",
    mktGeorgia: "Грузія",
    mktArmenia: "Вірменія",
    mktTurkey: "Туреччина",
    mktPersianGulf: "Країни Перської Затоки",
    connectWithSales: "📞 ЕКСПОРТНИЙ СТІЛ І ЗАПИТИ",
    contactUsTitle: "Зв'язатися з Нами",
    contactUsDesc: "Зв'яжіться з нашими експертами через пошту та WhatsApp для розрахунку FOB вартості доставки {product}.",
    whatsappHelp: "Допомога у WhatsApp",
    industrialExcellence: "📷 ДОКУМЕНТАЛЬНІ ФОТО ОПЕРАЦІЙ",
    galleryDetailsTitle: "Упаковочні та сортувальні процеси на півночі",
    galleryDetailsDesc: "Фотографії складських операцій, маркування та сортування перед завантаженням:",
    step01Title: "Міцні Пластикові Короби",
    step01Desc: "Конструкція лотків спроектована для тривалого транзиту через кордони.",
    step02Title: "Ручне Очищення Плодів",
    step02Desc: "Спеціалісти сортування перевіряють та очищують кожен плід для усунення дефектів.",
    step03Title: "Преміальний Експортний Калібр",
    step03Desc: "Відбір плодів однакового розміру згідно з жорсткими стандартами ЄС.",
    step04Title: "Вентильоване Укладання Палет",
    step04Desc: "Формування палет підтримує циркуляцію повітря всередині контейнера.",
    step05Title: "Лінія Механічного Контролю",
    step05Desc: "Перевірка щільності та загального стану плодів перед пакуванням.",
    step06Title: "Просушування та Видалення Вологи",
    step06Desc: "Підготовка грунтів та усунення вологості для унеможливлення появи цвілі.",
    clickToPreview: "ЗБІЛЬШИТИ ФОТО",
    reviewBoard: "СВІДОЦТВА І ПІДТВЕРДЖЕННЯ ПОСТАВОК",
    reviewTitle: "Оцінки та відгуки оптових покупців",
    reviewDesc: "Прочитайте відгуки представників компаній, які отримали наші вантажі у портах та складах.",
    verifiedAgent: "Верифікований Імпортер",
    registeredDispatch: "Дата проходження митної очистки",
    helpful: "Корисно? ",
    secureTimeline: "БЕЗПЕЧНИЙ ЗВІТ ПРО ЯКІСТЬ",
    submitTrade: "Додати оцінку за транш",
    submitTradeDesc: "Залиште коментар про збереження сорту, швидкість митниці та завантаження. Поля зі зірочкою обов'язкові.",
    productEvaluation: "Оцінка сортності товару *",
    outOfStars: "зірок / 5 рівнів",
    displayName: "Ваше Ім'я / Посада в компанії *",
    tradeEmail: "Корпоративний робочий Email *",
    wholesaleStatement: "Ваша експортна заява щодо вантажу *",
    statementPlaceholder: "Як прибули рефрижератори, оцініть роботу митниці, калібр та упаковку...",
    notRobot: "Я не робот",
    postStatement: "Додати звіт",
    cargoSuccess: "Відгук зафіксовано, коментар з'явиться після автоматичної перевірки."
  },
  hi: {
    backToDirectory: "उत्पाद निर्देशिका पर वापस जाएं",
    varietyStandard: "किस्म मानक",
    calibratedWeight: "कैलिब्रेटेड वजन",
    flavorProfile: "अरोमा और स्वाद",
    naturalColorTone: "प्राकृतिक रंग",
    coreDimensions: "मुख्य आयाम कलीवर",
    brixSugarIndex: "ब्रिक्स शुगर इंडेक्स",
    bulkPackingStyle: "थोक पैकिंग प्रारूप",
    hsCustomsCode: "एचएस सीमा शुल्क कोड",
    geographicalOrigin: "भौगोलिक उत्पत्ति",
    exportSeason: "निर्यात मौसम",
    primaryBatch: "★ प्राथमिक उत्कृष्ट बैच",
    reeferStability: "⚡ उच्च रेफर स्थिरता सूचक",
    sourcedInGilan: "🍀 100% गिलान सोर्स उत्पाद",
    datasheetTitle: "फसल विशिष्टता डेटापत्रक (Datasheet)",
    exportGrade: "निर्यात ग्रेड ए+",
    customRegulations: "निर्यात सीमा शुल्क नियम पारगमन मंजूरी तय करते हैं।",
    consultDesk: "हमारे निर्यात डेस्क से परामर्श करें 🟢",
    fastResponse: "5 मिनट से कम समय में त्वरित समाधान प्रतिक्रिया",
    yourName: "आपका नाम *",
    whatsappMobile: "आपका व्हाट्सएप मोबाइल नंबर *",
    yourEmail: "आपका ईमेल *",
    representativesContactNotice: "⚠️ हमारे व्यापार प्रतिनिधि अंग्रेजी, रूसी और फारसी में आपसे सीधे संपर्क करेंगे।",
    calculateFob: "गणन करें और संदेश भेजें FOB",
    processing: "प्रसंस्करण हो रहा है...",
    estimatesLoaded: "अनुमान तैयार!",
    estimatesLoadedDesc: "हमने सटीक शिपिंग कारकों का विश्लेषण और संकलन किया है। आप सीधे व्हाट्सएप पर बातचीत शुरू कर सकते हैं:",
    openSalesDesk: "बिक्री डेस्क खोलें",
    productNotFound: "उत्पाद नहीं मिला",
    productNotFoundDesc: "यह विशिष्ट कृषि उत्पाद हमारी सूची में नहीं मिला या बदल दिया गया है।",
    returnToDirectory: "उत्पादों पर वापस जाएं",
    tonnageCalculator: "इंटरैक्टिव रसद परिवहन क्षमता अनुमानक",
    metricTonnage: "वांछित टन भार (मीट्रिक टन):",
    calcEstimates: "सकल वजन के आधार पर वास्तविक समय रसद अनुमान स्वतः लागू किया गया।",
    tempParam: "फसल आंतरिक तापमान सूचकांक",
    humidityLevel: "सापेक्ष आर्द्रता स्तर अनुपात",
    preCoolingProtocol: "हाइड्रो-ट्रीटमेंट पूर्व-शीतलन प्रोटोकॉल",
    maxDuration: "अनुमानित सुरक्षित शेल्फ-लाइफ अवधि",
    freshExchange: "ताज़ा हवा वेंटिलेशन दर आवश्यकता",
    packagingWeight: "प्रति बॉक्स मानक अनुमानित वजन",
    reeferCap: "रेफ़र कंटेनर मानक क्षमता सूचक",
    cargoHandling: "कंटेनर विशेष हैंडलिंग निर्देश गाइड",
    // New Sections
    coldChainScheme: "● शीत-श्रृंखला संरक्षण योजना",
    coldChainTitle: "खेत से पैलेट तक सतर्क प्रशीतन प्रक्रिया",
    coldChainDesc: "हम कैस्पियन बागानों से अंतिम सीमा शुल्क जांच तक वायुमंडलीय संकेतकों की निगरानी करते हैं:",
    stage01Title: "प्री-कूलिंग हाइड्रो-इलाज",
    stage01Desc: "प्राकृतिक चीनी गिरावट को रोकने के लिए 4 घंटे के भीतर तापमान गिरा दिया जाता है।",
    stage02Title: "सटीक छँटाई प्रक्रिया",
    stage02Desc: "डिजिटल कैलिब्रेटर्स बाहरी शेल अखंडता और ब्लेमिश का आकलन करते हैं।",
    stage03Title: "नाइट्रोजन फ्लशिंग पैकिंग",
    stage03Desc: "वेंटिलेटेड बक्से एथिलीन अवशोषक के साथ पैक किए जाते हैं ताकि ताज़गी लॉक रहे।",
    stage04Title: "सीलबंद रीफर परिवहन",
    stage04Desc: "रेफ्रिजेरेटेड ट्रक लगातार टेलीमेट्री तापमान डेटा बनाए रखते हैं।",
    stepByStepPrep: "⚙️ कदम-दर-कदम तैयारी और प्रसंस्करण",
    prodPackingProcess: "उत्पादन और पैकेजिंग प्रक्रिया गाइड",
    prodPackingDesc: "हमारी प्रसंस्करण प्रणाली {product} की ताज़गी और गुणवत्ता सुनिश्चित करती है। सफाई के बाद, {product} को साफ टोकरियों में पैक किया जाता है।",
    complianceSafety: "🛡️ अनुपालन और सुरक्षा मानक प्रमाणन",
    qualitySafetyTitle: "उत्पाद सुरक्षा और उत्कृष्ट गुणवत्ता आश्वासन",
    qualitySafetyDesc: "GILAFRUIT में हमारी प्राथमिकता उत्पाद विश्वसनीयता है। हमारे विशेषज्ञ {product} पैकेजिंग और निरीक्षण को नियंत्रित करते हैं।",
    facilityWalkthrough: "सॉर्टिंग और कोल्ड स्टोरेज केंद्र प्रस्तुति",
    liveFootageTitle: "गिलान सॉर्टिंग हाउस लाइव वीडियो फुटेज",
    sortingFacility: "सॉर्टिंग सुविधा केंद्र",
    videoLength: "📹 लाइन प्रसंस्करण वीडियो - 2:14 मिनट",
    loadingVideoStream: "अस्तारा डिपो से लाइव वीडियो लोड हो रहा है...",
    closePlayback: "प्लेबैक बंद करें",
    faqHeader: "अक्सर पूछे जाने वाले प्रश्न",
    faqTitle: "वैश्विक व्यापार और खरीद निर्देश",
    secureSupplies: "🌟 सीधे उत्कृष्ट बागानों से थोक आपूर्ति ग्यारंटी",
    whyInternational: "अंतर्राष्ट्रीय खरीदार GilaFruit क्यों चुनते हैं?",
    volSupplyTitle: "नियमित और बड़े टन भार की विश्वसनीय आपूर्ति",
    volSupplyDesc: "अस्तारा बागानों से हम प्रति अभियान 2000 मीट्रिक टन तक आसानी से आपूर्ति संभाल सकते हैं।",
    coldWarehousingTitle: "एथिलीन नियंत्रण वाले उन्नत प्रशीतन गोदाम",
    coldWarehousingDesc: "नुकसान को रोकने के लिए नमी और एथिलीन स्तर को स्वचालित रूप से संतुलित किया जाता है।",
    customsTransitTitle: "फास्ट कस्टम क्लीयरेंस कूरियर सेवा",
    customsTransitDesc: "हमारा प्रतिनिधि सीधे अस्तारा बंदरगाह पर पादप-वयस्कता और EAC प्रमाण पत्र तेजी से जारी करवाता है।",
    packingPricingTitle: "बिना दलालों के प्रत्यक्ष फ़ैक्टरी थोक मूल्य",
    packingPricingDesc: "कटाई, प्रसंस्करण, लोडिंग के स्वचालित नियंत्रण द्वारा हम द्वितीयक दलालों को हटा देते हैं।",
    strategicAdvantages: "🚀 रणनीतिक लाभ और व्यापार अवसर",
    advantagesOfCompany: "हमारी कंपनी से थोक खरीद के अनूठे लाभ",
    advantagesIntro: "Gilafruit थोक स्तर पर उच्च गुणवत्ता के {product} के लिए बेजोड़ व्यापार प्रस्ताव प्रदान करता है:",
    adv1Title: "बड़ी मात्रा की विश्वसनीय आपूर्ति",
    adv1Desc: "किसानों के साथ दीर्घकालिक अनुबंधों के कारण, हम लगातार सर्वश्रेष्ठ {product} स्तर आपूर्ति कर सकते हैं।",
    adv2Title: "किस्मों और आकारों की प्रचुरता",
    adv2Desc: "विदेशी सुपरमार्केट आवश्यकताओं के अनुसार वर्गीकृत {product} के विभिन्न ग्रेड उपलब्ध हैं।",
    adv3Title: "कस्टम बॉक्सिंग पैकेजिंग विकल्प",
    adv3Desc: "दीर्घकालिक परिवहन को सहन करने के लिए खरीदार की इच्छा के अनुसार बक्से मजबूत किए जाते हैं।",
    adv4Title: "तेज़ तापमान-नियंत्रित रीफर डिलीवरी",
    adv4Desc: "ताज़गी बनाए रखने के लिए अनुकूल रसद और तेज़ रीफर ट्रकों का उपयोग किया जाता है।",
    adv5Title: "ईमानदार और न्यूनतम थोक मूल्य",
    adv5Desc: "दलालों को हटाकर हम ईरानी {product} पर सर्वोत्तम सीधा और प्रतिस्पर्धी व्यापार मूल्य देते हैं।",
    exportDestinations: "🌍 अंतर्राष्ट्रीय निर्यात क्षेत्र और सीमाएं",
    targetMarkets: "लक्षित निर्यात बाज़ार",
    targetMarketsDesc: "{product} उत्पाद रूस, बेलारूस, अज़रबैजान, जॉर्जिया, आर्मेनिया, तुर्की और खाड़ी देशों को निर्यात होता है।",
    mktRussia: "रूस संघ",
    mktBelarus: "बेलारूस",
    mktAzerbaijan: "अज़रबैजान",
    mktGeorgia: "जॉर्जिया",
    mktArmenia: "आर्मेनिया",
    mktTurkey: "तुर्की",
    mktPersianGulf: "फारस की खाड़ी के देश",
    connectWithSales: "📞 अंतर्राष्ट्रीय बिक्री विभाग हॉटलाइन",
    contactUsTitle: "हमसे संपर्क करें",
    contactUsDesc: "थोक आवश्यकताओं और लोडिंग विकल्पों पर सीधा परामर्श के लिए WhatsApp या ईमेल पर हमसे संपर्क करें।",
    whatsappHelp: "व्हाट्सएप चैट सहायता",
    industrialExcellence: "📷 फ़ैक्टरी प्रसंस्करण प्रलेखन छवियां",
    galleryDetailsTitle: "गिलान अंतर्राष्ट्रीय सॉर्टिंग और पैकिंग हाउस",
    galleryDetailsDesc: "निर्यात के लिए माल को पैक और कड़ा करने की प्रक्रियाओं की तस्वीरें:",
    step01Title: "स्वच्छ मजबूत पैकेजिंग बक्से",
    step01Desc: "अंतरराष्ट्रीय सीमा पार करने के अनुकूल उच्च घनत्व वाले सुरक्षित बॉक्स लंबे समय के लिए।",
    step02Title: "कर्मचारियों द्वारा मैन्युअल प्रारंभिक छँटाई",
    step02Desc: "घटिया फसल को प्रारंभिक चरण में ही अनुभवी स्टाफ द्वारा बाहर निकालना।",
    step03Title: "प्रीमियम निर्यात ग्रेड वर्गीकरण",
    step03Desc: "बराबर आकार के टुकड़ों में सॉर्ट करके सर्वश्रेष्ठ हाइपरमार्केट गुणवत्ता रेटिंग देना।",
    step04Title: "हवा चलने के अनुकूल पैलेट स्टैकिंग",
    step04Desc: "ट्रक के अंदर प्रशीतन हवा को पारित करने के लिए बक्से को पैलेट में वैज्ञानिक रूप से रखना।",
    step05Title: "स्वचालित यांत्रिक सॉर्टिंग इकाइयां",
    step05Desc: "फसल की सतह की अखंडता की जाँच के लिए ऑप्टिकल सेंसर तकनीक का उपयोग।",
    step06Title: "सुखाने की अंतिम प्रक्रिया और नमी नियंत्रण",
    step06Desc: "लंबी लाइनों में सड़ने से रोकने के लिए नमी को ठीक स्तर तक कम करना।",
    clickToPreview: "छवि का बड़ा पूर्वावलोकन",
    reviewBoard: "थोक व्यापारी और खरीदार मंच समीक्षाएं",
    reviewTitle: "साझा व्यापार और कस्टम एजेंटों के विचार",
    reviewDesc: "GilaFruit उत्पादों का आयात करने और सीमा शुल्क का सफल पारगमन करने वाले खरीदारों के प्रमाणन वक्तव्य।",
    verifiedAgent: "सत्यापित आयातक",
    registeredDispatch: "सीमा शुल्क निकासी और प्रेषण तिथि",
    helpful: "क्या यह मददगार था? ",
    secureTimeline: "व्यावसायिक गुणवत्ता आश्वासन प्रमाणपत्र प्रपत्र",
    submitTrade: "व्यावसायिक प्रतिक्रिया दर्ज करें",
    submitTradeDesc: "परिवहन गुणवत्ता, रीति-रिवाजों और ग्रेडिंग के बारे में समीक्षा दर्ज करें। तारांकित क्षेत्र आवश्यक हैं।",
    productEvaluation: "उत्पाद गुणवत्ता रेटिंग *",
    outOfStars: "तारे / 5 उत्कृष्ट स्तर सूचक",
    displayName: "आपका पूरा नाम / कंपनी पद *",
    tradeEmail: "कंपनी व्यवसाय ईमेल *",
    wholesaleStatement: "आपका व्यावसायिक विवरण वक्तव्य *",
    statementPlaceholder: "कैलिब्रेशन ग्रेड, सीमा बिंदुओं पर रीति-रिवाजों और परिवहन गुणवत्ता का वर्णन करें...",
    notRobot: "मैं रोबोट नहीं हूँ",
    postStatement: "प्रतिक्रिया प्रकाशित करें",
    cargoSuccess: "फीडबैक प्राप्त हुआ! सत्यापन के बाद प्रकाशित किया जाएगा।"
  }
};
